package utils.color;

import java.util.HashMap;
import java.util.Map;

import java.awt.Color;

public abstract class BaseColors {
	protected static final Map<String, Color> nameToColor = new HashMap<>();
	protected static final Map<Integer, String> colorToName = new HashMap<>();
	
	protected static void registerColor(String name, Color color) {
		if (name == null || color == null) {
			throw new IllegalArgumentException("Color name and color must not be null");
		}

		name = name.toUpperCase();
		Color existingColor = nameToColor.get(name);

		if (existingColor == null) {
			nameToColor.put(name, color);
			String priorName = colorToName.putIfAbsent(color.getRGB(), name);
			if (priorName != null && !priorName.equals(name)) {
				/*System.err.printf(
					"Warning: color %s already registered to name '%s', now also registered as '%s'%n",
					color, priorName, name
				);*/
			}
		} else if (color.getRGB() == existingColor.getRGB()) {
			/*System.err.printf(
				"Warning: color name '%s' already registered with identical color %s%n",
				name, color
			);*/
		} else {
			throw new IllegalArgumentException(String.format(
				"Color name '%s' already registered with a different color: existing=%s, new=%s",
				name, existingColor, color
			));
		}
	}

	public static final Color ABSOLUTE_ZERO = new Color(0, 72, 186);
	public static final Color ACID_GREEN = new Color(176, 191, 26);
	public static final Color AERO = new Color(124, 185, 232);
	public static final Color AFRICAN_VIOLET = new Color(178, 132, 190);
	public static final Color AIR_SUPERIORITY_BLUE = new Color(114, 160, 193);
	public static final Color ALICE_BLUE = new Color(240, 248, 255);
	public static final Color ALIZARIN = new Color(219, 45, 67);
	public static final Color ALLOY_ORANGE = new Color(196, 98, 16);
	public static final Color ALMOND = new Color(238, 217, 196);
	public static final Color AMARANTH_DEEP_PURPLE = new Color(159, 43, 104);
	public static final Color AMARANTH_PINK = new Color(241, 156, 187);
	public static final Color AMARANTH_PURPLE = new Color(171, 39, 79);
	public static final Color AMAZON = new Color(59, 122, 87);
	public static final Color AMBER = new Color(255, 191, 0);
	public static final Color AMETHYST = new Color(153, 102, 204);
	public static final Color ANDROID_GREEN = new Color(61, 220, 132);
	public static final Color ANTIQUE_BRASS = new Color(200, 138, 101);
	public static final Color ANTIQUE_BRONZE = new Color(102, 93, 30);
	public static final Color ANTIQUE_FUCHSIA = new Color(145, 92, 131);
	public static final Color ANTIQUE_RUBY = new Color(132, 27, 45);
	public static final Color ANTIQUE_WHITE = new Color(250, 235, 215);
	public static final Color APRICOT = new Color(251, 206, 177);
	public static final Color AQUA = new Color(0, 255, 255);
	public static final Color AQUAMARINE = new Color(127, 255, 212);
	public static final Color ARCTIC_LIME = new Color(208, 255, 20);
	public static final Color ARTICHOKE_GREEN = new Color(75, 111, 68);
	public static final Color ARYLIDE_YELLOW = new Color(233, 214, 107);
	public static final Color ASH_GRAY = new Color(178, 190, 181);
	public static final Color ATOMIC_TANGERINE = new Color(255, 153, 102);
	public static final Color AUREOLIN = new Color(253, 238, 0);
	public static final Color AZURE = new Color(0, 127, 255);
	public static final Color BDAZZLED_BLUE = new Color(46, 88, 148);
	public static final Color BABY_BLUE = new Color(137, 207, 240);
	public static final Color BABY_BLUE_EYES = new Color(161, 202, 241);
	public static final Color BABY_PINK = new Color(244, 194, 194);
	public static final Color BABY_POWDER = new Color(254, 254, 250);
	public static final Color BAKER_MILLER_PINK = new Color(255, 145, 175);
	public static final Color BANANA_MANIA = new Color(250, 231, 181);
	public static final Color BARBIE_PINK = new Color(218, 24, 132);
	public static final Color BARN_RED = new Color(124, 10, 2);
	public static final Color BATTLESHIP_GREY = new Color(132, 132, 130);
	public static final Color BEAU_BLUE = new Color(188, 212, 230);
	public static final Color BEAVER = new Color(159, 129, 112);
	public static final Color BEIGE = new Color(245, 245, 220);
	public static final Color BIG_DIP_ORUBY = new Color(156, 37, 66);
	public static final Color BISQUE = new Color(255, 228, 196);
	public static final Color BISTRE = new Color(61, 43, 31);
	public static final Color BISTRE_BROWN = new Color(150, 113, 23);
	public static final Color BITTER_LEMON = new Color(202, 224, 13);
	public static final Color BLACK = new Color(0, 0, 0);
	public static final Color BLACK_SHADOWS = new Color(191, 175, 178);
	public static final Color BLACK_BEAN = new Color(61, 12, 2);
	public static final Color BLACK_CORAL = new Color(84, 98, 111);
	public static final Color BLACK_OLIVE = new Color(59, 60, 54);
	public static final Color BLANCHED_ALMOND = new Color(255, 235, 205);
	public static final Color BLAST_OFF_BRONZE = new Color(165, 113, 100);
	public static final Color BLEU_DE_FRANCE = new Color(49, 140, 231);
	public static final Color BLIZZARD_BLUE = new Color(172, 229, 238);
	public static final Color BLOOD_RED = new Color(102, 0, 0);
	public static final Color BLUE = new Color(0, 0, 255);
	public static final Color BLUE_BELL = new Color(162, 162, 208);
	public static final Color BLUE_JEANS = new Color(93, 173, 236);
	public static final Color BLUE_SAPPHIRE = new Color(18, 97, 128);
	public static final Color BLUE_YONDER = new Color(80, 114, 167);
	public static final Color BLUE_GRAY = new Color(102, 153, 204);
	public static final Color BLUE_VIOLET = new Color(138, 43, 226);
	public static final Color BLUETIFUL = new Color(60, 105, 231);
	public static final Color BLUSH = new Color(222, 93, 131);
	public static final Color BOLE = new Color(121, 68, 59);
	public static final Color BONE = new Color(227, 218, 201);
	public static final Color BRICK_RED = new Color(203, 65, 84);
	public static final Color BRIGHT_LILAC = new Color(216, 145, 239);
	public static final Color BRIGHT_YELLOW = new Color(255, 170, 29);
	public static final Color BRITISH_RACING_GREEN = new Color(0, 66, 37);
	public static final Color BRONZE = new Color(205, 127, 50);
	public static final Color BROWN = new Color(150, 75, 0);
	public static final Color BROWN_SUGAR = new Color(175, 110, 77);
	public static final Color BUD_GREEN = new Color(123, 182, 97);
	public static final Color BUFF = new Color(255, 198, 128);
	public static final Color BURGUNDY = new Color(128, 0, 32);
	public static final Color BURLYWOOD = new Color(222, 184, 135);
	public static final Color BURNISHED_BROWN = new Color(161, 122, 116);
	public static final Color BURNT_ORANGE = new Color(204, 85, 0);
	public static final Color BURNT_SIENNA = new Color(233, 116, 81);
	public static final Color BURNT_UMBER = new Color(138, 51, 36);
	public static final Color BYZANTINE = new Color(189, 51, 164);
	public static final Color BYZANTIUM = new Color(112, 41, 99);
	public static final Color CADET_BLUE = new Color(95, 158, 160);
	public static final Color CADET_GREY = new Color(145, 163, 176);
	public static final Color CADMIUM_GREEN = new Color(0, 107, 60);
	public static final Color CADMIUM_ORANGE = new Color(237, 135, 45);
	public static final Color CAFÉ_AU_LAIT = new Color(166, 123, 91);
	public static final Color CAFÉ_NOIR = new Color(75, 54, 33);
	public static final Color CAMBRIDGE_BLUE = new Color(163, 193, 173);
	public static final Color CAMEL = new Color(193, 154, 107);
	public static final Color CAMEO_PINK = new Color(239, 187, 204);
	public static final Color CANARY = new Color(255, 255, 153);
	public static final Color CANARY_YELLOW = new Color(255, 239, 0);
	public static final Color CANDY_PINK = new Color(228, 113, 122);
	public static final Color CARDINAL = new Color(196, 30, 58);
	public static final Color CARIBBEAN_GREEN = new Color(0, 204, 153);
	public static final Color CARMINE = new Color(150, 0, 24);
	public static final Color CARNATION_PINK = new Color(255, 166, 201);
	public static final Color CARNELIAN = new Color(179, 27, 27);
	public static final Color CAROLINA_BLUE = new Color(86, 160, 211);
	public static final Color CARROT_ORANGE = new Color(237, 145, 33);
	public static final Color CATAWBA = new Color(112, 54, 66);
	public static final Color CEDAR_CHEST = new Color(201, 90, 73);
	public static final Color CELADON = new Color(172, 225, 175);
	public static final Color CELESTE = new Color(178, 255, 255);
	public static final Color CERISE = new Color(222, 49, 99);
	public static final Color CERULEAN = new Color(0, 123, 167);
	public static final Color CERULEAN_BLUE = new Color(42, 82, 190);
	public static final Color CERULEAN_FROST = new Color(109, 155, 195);
	public static final Color CHAMPAGNE = new Color(247, 231, 206);
	public static final Color CHAMPAGNE_PINK = new Color(241, 221, 207);
	public static final Color CHARCOAL = new Color(54, 69, 79);
	public static final Color CHARM_PINK = new Color(230, 143, 172);
	public static final Color CHARTREUSE = new Color(128, 255, 0);
	public static final Color CHERRY_BLOSSOM_PINK = new Color(255, 183, 197);
	public static final Color CHESTNUT = new Color(149, 69, 53);
	public static final Color CHILI_RED = new Color(226, 61, 40);
	public static final Color CHINA_PINK = new Color(222, 111, 161);
	public static final Color CHINESE_RED = new Color(170, 56, 30);
	public static final Color CHINESE_VIOLET = new Color(133, 96, 136);
	public static final Color CHINESE_YELLOW = new Color(255, 178, 0);
	public static final Color CHOCOLATE = new Color(123, 63, 0);
	public static final Color CINEREOUS = new Color(152, 129, 123);
	public static final Color CINNABAR = new Color(227, 66, 52);
	public static final Color CINNAMON_SATIN = new Color(205, 96, 126);
	public static final Color CITRINE = new Color(228, 208, 10);
	public static final Color CITRON = new Color(159, 169, 31);
	public static final Color CLARET = new Color(127, 23, 52);
	public static final Color COFFEE = new Color(111, 78, 55);
	public static final Color COLUMBIA_BLUE = new Color(185, 217, 235);
	public static final Color CONGO_PINK = new Color(248, 131, 121);
	public static final Color COOL_GREY = new Color(140, 146, 172);
	public static final Color COPPER = new Color(184, 115, 51);
	public static final Color COPPER_PENNY = new Color(173, 111, 105);
	public static final Color COPPER_RED = new Color(203, 109, 81);
	public static final Color COPPER_ROSE = new Color(153, 102, 102);
	public static final Color COQUELICOT = new Color(255, 56, 0);
	public static final Color CORAL = new Color(255, 127, 80);
	public static final Color CORAL_PINK = new Color(248, 131, 121);
	public static final Color CORDOVAN = new Color(137, 63, 69);
	public static final Color CORN = new Color(251, 236, 93);
	public static final Color CORNFLOWER_BLUE = new Color(100, 149, 237);
	public static final Color CORNSILK = new Color(255, 248, 220);
	public static final Color COSMIC_COBALT = new Color(46, 45, 136);
	public static final Color COSMIC_LATTE = new Color(255, 248, 231);
	public static final Color COTTON_CANDY = new Color(255, 188, 217);
	public static final Color COYOTE_BROWN = new Color(129, 97, 60);
	public static final Color CREAM = new Color(255, 253, 208);
	public static final Color CRIMSON = new Color(220, 20, 60);
	public static final Color CULTURED_PEARL = new Color(245, 245, 245);
	public static final Color CYAN = new Color(0, 255, 255);
	public static final Color CYBER_GRAPE = new Color(88, 66, 124);
	public static final Color CYBER_YELLOW = new Color(255, 211, 0);
	public static final Color CYCLAMEN = new Color(245, 111, 161);
	public static final Color DANDELION = new Color(254, 216, 93);
	public static final Color DARK_BROWN = new Color(101, 67, 33);
	public static final Color DARK_BYZANTIUM = new Color(93, 57, 84);
	public static final Color DARK_CYAN = new Color(0, 139, 139);
	public static final Color DARK_ELECTRIC_BLUE = new Color(83, 104, 120);
	public static final Color DARK_GOLDENROD = new Color(184, 134, 11);
	public static final Color DARK_GREEN = new Color(0, 100, 0);
	public static final Color DARK_JUNGLE_GREEN = new Color(26, 36, 33);
	public static final Color DARK_KHAKI = new Color(189, 183, 107);
	public static final Color DARK_LAVA = new Color(72, 60, 50);
	public static final Color DARK_LIVER = new Color(84, 61, 55);
	public static final Color DARK_MAGENTA = new Color(139, 0, 139);
	public static final Color DARK_OLIVE_GREEN = new Color(85, 107, 47);
	public static final Color DARK_ORANGE = new Color(255, 140, 0);
	public static final Color DARK_ORCHID = new Color(153, 50, 204);
	public static final Color DARK_PURPLE = new Color(48, 25, 52);
	public static final Color DARK_RED = new Color(139, 0, 0);
	public static final Color DARK_SALMON = new Color(233, 150, 122);
	public static final Color DARK_SEA_GREEN = new Color(143, 188, 143);
	public static final Color DARK_SIENNA = new Color(60, 20, 20);
	public static final Color DARK_SKY_BLUE = new Color(140, 190, 214);
	public static final Color DARK_SLATE_BLUE = new Color(72, 61, 139);
	public static final Color DARK_SLATE_GRAY = new Color(47, 79, 79);
	public static final Color DARK_SPRING_GREEN = new Color(23, 114, 69);
	public static final Color DARK_TURQUOISE = new Color(0, 206, 209);
	public static final Color DARK_VIOLET = new Color(148, 0, 211);
	public static final Color DAVYS_GREY = new Color(85, 85, 85);
	public static final Color DEEP_SPACE_SPARKLE = new Color(74, 100, 108);
	public static final Color DEEP_CERISE = new Color(218, 50, 135);
	public static final Color DEEP_CHAMPAGNE = new Color(250, 214, 165);
	public static final Color DEEP_CHESTNUT = new Color(185, 78, 72);
	public static final Color DEEP_JUNGLE_GREEN = new Color(0, 75, 73);
	public static final Color DEEP_PINK = new Color(255, 20, 147);
	public static final Color DEEP_SAFFRON = new Color(255, 153, 51);
	public static final Color DEEP_SKY_BLUE = new Color(0, 191, 255);
	public static final Color DEEP_TAUPE = new Color(126, 94, 96);
	public static final Color DENIM = new Color(21, 96, 189);
	public static final Color DENIM_BLUE = new Color(34, 67, 182);
	public static final Color DESERT = new Color(193, 154, 107);
	public static final Color DESERT_SAND = new Color(237, 201, 175);
	public static final Color DIM_GRAY = new Color(105, 105, 105);
	public static final Color DODGER_BLUE = new Color(30, 144, 255);
	public static final Color DRAB_DARK_BROWN = new Color(74, 65, 42);
	public static final Color DUKE_BLUE = new Color(0, 0, 156);
	public static final Color DUTCH_WHITE = new Color(239, 223, 187);
	public static final Color EBONY = new Color(85, 93, 80);
	public static final Color ECRU = new Color(194, 178, 128);
	public static final Color EERIE_BLACK = new Color(27, 27, 27);
	public static final Color EGGPLANT = new Color(97, 64, 81);
	public static final Color EGGSHELL = new Color(240, 234, 214);
	public static final Color ELECTRIC_LIME = new Color(204, 255, 0);
	public static final Color ELECTRIC_PURPLE = new Color(191, 0, 255);
	public static final Color ELECTRIC_VIOLET = new Color(143, 0, 255);
	public static final Color EMERALD = new Color(80, 200, 120);
	public static final Color EMINENCE = new Color(108, 48, 130);
	public static final Color ENGLISH_LAVENDER = new Color(180, 131, 149);
	public static final Color ENGLISH_RED = new Color(171, 75, 82);
	public static final Color ENGLISH_VERMILLION = new Color(204, 71, 75);
	public static final Color ENGLISH_VIOLET = new Color(86, 60, 92);
	public static final Color ERIN = new Color(0, 255, 64);
	public static final Color ETON_BLUE = new Color(150, 200, 162);
	public static final Color FALLOW = new Color(193, 154, 107);
	public static final Color FALU_RED = new Color(128, 24, 24);
	public static final Color FANDANGO = new Color(181, 51, 137);
	public static final Color FANDANGO_PINK = new Color(222, 82, 133);
	public static final Color FAWN = new Color(229, 170, 112);
	public static final Color FERN_GREEN = new Color(79, 121, 66);
	public static final Color FIELD_DRAB = new Color(108, 84, 30);
	public static final Color FIERY_ROSE = new Color(255, 84, 112);
	public static final Color FINN = new Color(104, 48, 104);
	public static final Color FIRE_ENGINE_RED = new Color(206, 32, 41);
	public static final Color FIREBRICK = new Color(178, 34, 34);
	public static final Color FLAME = new Color(226, 88, 34);
	public static final Color FLAX = new Color(238, 220, 130);
	public static final Color FLIRT = new Color(162, 0, 109);
	public static final Color FLORAL_WHITE = new Color(255, 250, 240);
	public static final Color FOREST_GREEN = new Color(34, 139, 34);
	public static final Color FRENCH_BEIGE = new Color(166, 123, 91);
	public static final Color FRENCH_BISTRE = new Color(133, 109, 77);
	public static final Color FRENCH_BLUE = new Color(0, 114, 187);
	public static final Color FRENCH_FUCHSIA = new Color(253, 63, 146);
	public static final Color FRENCH_LILAC = new Color(134, 96, 142);
	public static final Color FRENCH_LIME = new Color(158, 253, 56);
	public static final Color FRENCH_MAUVE = new Color(212, 115, 212);
	public static final Color FRENCH_PINK = new Color(253, 108, 158);
	public static final Color FRENCH_RASPBERRY = new Color(199, 44, 72);
	public static final Color FRENCH_SKY_BLUE = new Color(119, 181, 254);
	public static final Color FRENCH_VIOLET = new Color(136, 6, 206);
	public static final Color FROSTBITE = new Color(233, 54, 167);
	public static final Color FUCHSIA = new Color(255, 0, 255);
	public static final Color FULVOUS = new Color(228, 132, 0);
	public static final Color FUZZY_WUZZY = new Color(135, 66, 31);
	public static final Color GO_GREEN = new Color(0, 171, 102);
	public static final Color GAINSBORO = new Color(220, 220, 220);
	public static final Color GAMBOGE = new Color(228, 155, 15);
	public static final Color GENERIC_VIRIDIAN = new Color(0, 127, 102);
	public static final Color GHOST_WHITE = new Color(248, 248, 255);
	public static final Color GLAUCOUS = new Color(96, 130, 182);
	public static final Color GLOSSY_GRAPE = new Color(171, 146, 179);
	public static final Color GOLD = new Color(230, 190, 138);
	public static final Color GOLD_FUSION = new Color(133, 117, 78);
	public static final Color GOLDEN_BROWN = new Color(153, 101, 21);
	public static final Color GOLDEN_POPPY = new Color(252, 194, 0);
	public static final Color GOLDEN_YELLOW = new Color(255, 223, 0);
	public static final Color GOLDENROD = new Color(218, 165, 32);
	public static final Color GOTHAM_GREEN = new Color(0, 87, 63);
	public static final Color GRANITE_GRAY = new Color(103, 103, 103);
	public static final Color GRANNY_SMITH_APPLE = new Color(168, 228, 160);
	public static final Color GRAY = new Color(190, 190, 190);
	public static final Color GREEN = new Color(0, 255, 0);
	public static final Color GREEN_LIZARD = new Color(167, 244, 50);
	public static final Color GREEN_SHEEN = new Color(110, 174, 161);
	public static final Color GREEN_BLUE = new Color(17, 100, 180);
	public static final Color GUNMETAL = new Color(42, 52, 57);
	public static final Color HANSA_YELLOW = new Color(233, 214, 107);
	public static final Color HARLEQUIN = new Color(63, 255, 0);
	public static final Color HARVEST_GOLD = new Color(218, 145, 0);
	public static final Color HEAT_WAVE = new Color(255, 122, 0);
	public static final Color HELIOTROPE = new Color(223, 115, 255);
	public static final Color HELIOTROPE_GRAY = new Color(170, 152, 169);
	public static final Color HOLLYWOOD_CERISE = new Color(244, 0, 161);
	public static final Color HONOLULU_BLUE = new Color(0, 109, 176);
	public static final Color HOOKERS_GREEN = new Color(73, 121, 107);
	public static final Color HOT_MAGENTA = new Color(255, 29, 206);
	public static final Color HOT_PINK = new Color(255, 105, 180);
	public static final Color HUNTER_GREEN = new Color(53, 94, 59);
	public static final Color ICEBERG = new Color(113, 166, 210);
	public static final Color ILLUMINATING_EMERALD = new Color(49, 145, 119);
	public static final Color IMPERIAL_RED = new Color(237, 41, 57);
	public static final Color INCHWORM = new Color(178, 236, 93);
	public static final Color INDEPENDENCE = new Color(76, 81, 109);
	public static final Color INDIA_GREEN = new Color(19, 136, 8);
	public static final Color INDIAN_RED = new Color(205, 92, 92);
	public static final Color INDIAN_YELLOW = new Color(227, 168, 87);
	public static final Color INDIGO = new Color(106, 93, 255);
	public static final Color INDIGO_DYE = new Color(0, 65, 106);
	public static final Color INTERNATIONAL_KLEIN_BLUE = new Color(19, 10, 143);
	public static final Color INTERNATIONAL_ORANGE = new Color(192, 54, 44);
	public static final Color IRRESISTIBLE = new Color(179, 68, 108);
	public static final Color ISABELLINE = new Color(244, 240, 236);
	public static final Color ITALIAN_SKY_BLUE = new Color(178, 255, 255);
	public static final Color IVORY = new Color(255, 255, 240);
	public static final Color JAPANESE_CARMINE = new Color(157, 41, 51);
	public static final Color JAPANESE_VIOLET = new Color(91, 50, 86);
	public static final Color JASMINE = new Color(248, 222, 126);
	public static final Color JAZZBERRY_JAM = new Color(165, 11, 94);
	public static final Color JET = new Color(52, 52, 52);
	public static final Color JONQUIL = new Color(244, 202, 22);
	public static final Color JUNE_BUD = new Color(189, 218, 87);
	public static final Color JUNGLE_GREEN = new Color(41, 171, 135);
	public static final Color KSU_PURPLE = new Color(81, 40, 136);
	public static final Color KELLY_GREEN = new Color(76, 187, 23);
	public static final Color KEPPEL = new Color(58, 176, 158);
	public static final Color KEY_LIME = new Color(232, 244, 140);
	public static final Color KHAKI = new Color(240, 230, 140);
	public static final Color KOBE = new Color(136, 45, 23);
	public static final Color KOBI = new Color(231, 159, 196);
	public static final Color KOBICHA = new Color(107, 68, 35);
	public static final Color LANGUID_LAVENDER = new Color(214, 202, 221);
	public static final Color LAPIS_LAZULI = new Color(38, 97, 156);
	public static final Color LASER_LEMON = new Color(255, 255, 102);
	public static final Color LAUREL_GREEN = new Color(169, 186, 157);
	public static final Color LAVA = new Color(207, 16, 32);
	public static final Color LAVENDER = new Color(181, 126, 220);
	public static final Color LAVENDER_BLUE = new Color(204, 204, 255);
	public static final Color LAVENDER_BLUSH = new Color(255, 240, 245);
	public static final Color LAVENDER_GRAY = new Color(196, 195, 208);
	public static final Color LAWN_GREEN = new Color(124, 252, 0);
	public static final Color LEMON = new Color(255, 247, 0);
	public static final Color LEMON_CHIFFON = new Color(255, 250, 205);
	public static final Color LEMON_CURRY = new Color(204, 160, 29);
	public static final Color LEMON_GLACIER = new Color(253, 255, 0);
	public static final Color LEMON_MERINGUE = new Color(246, 234, 190);
	public static final Color LEMON_YELLOW = new Color(255, 244, 79);
	public static final Color LIBERTY = new Color(84, 90, 167);
	public static final Color LIGHT_FRENCH_BEIGE = new Color(200, 173, 127);
	public static final Color LIGHT_BLUE = new Color(173, 216, 230);
	public static final Color LIGHT_CORAL = new Color(240, 128, 128);
	public static final Color LIGHT_CORNFLOWER_BLUE = new Color(147, 204, 234);
	public static final Color LIGHT_CYAN = new Color(224, 255, 255);
	public static final Color LIGHT_GOLDENROD_YELLOW = new Color(250, 250, 210);
	public static final Color LIGHT_GRAY = new Color(211, 211, 211);
	public static final Color LIGHT_GREEN = new Color(144, 238, 144);
	public static final Color LIGHT_ORANGE = new Color(254, 216, 177);
	public static final Color LIGHT_PERIWINKLE = new Color(197, 203, 225);
	public static final Color LIGHT_PINK = new Color(255, 182, 193);
	public static final Color LIGHT_PURPLE = new Color(216, 191, 216);
	public static final Color LIGHT_SALMON = new Color(255, 160, 122);
	public static final Color LIGHT_SEA_GREEN = new Color(32, 178, 170);
	public static final Color LIGHT_SKY_BLUE = new Color(135, 206, 250);
	public static final Color LIGHT_SLATE_GRAY = new Color(119, 136, 153);
	public static final Color LIGHT_STEEL_BLUE = new Color(176, 196, 222);
	public static final Color LIGHT_YELLOW = new Color(255, 255, 224);
	public static final Color LILAC = new Color(200, 162, 200);
	public static final Color LILAC_LUSTER = new Color(174, 152, 170);
	public static final Color LIME = new Color(191, 255, 0);
	public static final Color LIME_GREEN = new Color(50, 205, 50);
	public static final Color LINCOLN_GREEN = new Color(25, 89, 5);
	public static final Color LINEN = new Color(250, 240, 230);
	public static final Color LION = new Color(222, 204, 156);
	public static final Color LISERAN_PURPLE = new Color(222, 111, 161);
	public static final Color LITTLE_BOY_BLUE = new Color(108, 160, 220);
	public static final Color LIVER = new Color(103, 76, 71);
	public static final Color LIVER_CHESTNUT = new Color(152, 116, 86);
	public static final Color LIVID = new Color(102, 153, 204);
	public static final Color MSU_GREEN = new Color(24, 69, 59);
	public static final Color MACARONI_AND_CHEESE = new Color(255, 189, 136);
	public static final Color MADDER_LAKE = new Color(204, 51, 54);
	public static final Color MAGENTA = new Color(255, 0, 255);
	public static final Color MAGENTA_HAZE = new Color(159, 69, 118);
	public static final Color MAGIC_MINT = new Color(170, 240, 209);
	public static final Color MAGNOLIA = new Color(242, 232, 215);
	public static final Color MAHOGANY = new Color(192, 64, 0);
	public static final Color MAIZE = new Color(251, 236, 93);
	public static final Color MAJORELLE_BLUE = new Color(96, 80, 220);
	public static final Color MALACHITE = new Color(11, 218, 81);
	public static final Color MANATEE = new Color(151, 154, 170);
	public static final Color MANDARIN = new Color(243, 122, 72);
	public static final Color MANGO = new Color(253, 190, 2);
	public static final Color MANGO_TANGO = new Color(255, 130, 67);
	public static final Color MANTIS = new Color(116, 195, 101);
	public static final Color MARDI_GRAS = new Color(136, 0, 133);
	public static final Color MARIGOLD = new Color(234, 162, 33);
	public static final Color MAROON = new Color(195, 33, 72);
	public static final Color MAUVE = new Color(224, 176, 255);
	public static final Color MAUVE_TAUPE = new Color(145, 95, 109);
	public static final Color MAUVELOUS = new Color(239, 152, 170);
	public static final Color MAXIMUM_BLUE = new Color(71, 171, 204);
	public static final Color MAXIMUM_BLUE_GREEN = new Color(48, 191, 191);
	public static final Color MAXIMUM_BLUE_PURPLE = new Color(172, 172, 230);
	public static final Color MAXIMUM_GREEN = new Color(94, 140, 49);
	public static final Color MAXIMUM_GREEN_YELLOW = new Color(217, 230, 80);
	public static final Color MAXIMUM_PURPLE = new Color(115, 51, 128);
	public static final Color MAXIMUM_RED = new Color(217, 33, 33);
	public static final Color MAXIMUM_RED_PURPLE = new Color(166, 58, 121);
	public static final Color MAXIMUM_YELLOW = new Color(250, 250, 55);
	public static final Color MAXIMUM_YELLOW_RED = new Color(242, 186, 73);
	public static final Color MAY_GREEN = new Color(76, 145, 65);
	public static final Color MAYA_BLUE = new Color(115, 194, 251);
	public static final Color MEDIUM_AQUAMARINE = new Color(102, 221, 170);
	public static final Color MEDIUM_BLUE = new Color(0, 0, 205);
	public static final Color MEDIUM_CANDY_APPLE_RED = new Color(226, 6, 44);
	public static final Color MEDIUM_CARMINE = new Color(175, 64, 53);
	public static final Color MEDIUM_CHAMPAGNE = new Color(243, 229, 171);
	public static final Color MEDIUM_ORCHID = new Color(186, 85, 211);
	public static final Color MEDIUM_PURPLE = new Color(147, 112, 219);
	public static final Color MEDIUM_SEA_GREEN = new Color(60, 179, 113);
	public static final Color MEDIUM_SLATE_BLUE = new Color(123, 104, 238);
	public static final Color MEDIUM_SPRING_GREEN = new Color(0, 250, 154);
	public static final Color MEDIUM_TURQUOISE = new Color(72, 209, 204);
	public static final Color MEDIUM_VIOLET_RED = new Color(199, 21, 133);
	public static final Color MELLOW_APRICOT = new Color(248, 184, 120);
	public static final Color MELLOW_YELLOW = new Color(248, 222, 126);
	public static final Color MELON = new Color(254, 186, 173);
	public static final Color METALLIC_SEAWEED = new Color(10, 126, 140);
	public static final Color METALLIC_SUNBURST = new Color(156, 124, 56);
	public static final Color METALLIC_GOLD = new Color(211, 175, 55);
	public static final Color MEXICAN_PINK = new Color(228, 0, 124);
	public static final Color MIDDLE_BLUE = new Color(126, 212, 230);
	public static final Color MIDDLE_BLUE_GREEN = new Color(141, 217, 204);
	public static final Color MIDDLE_BLUE_PURPLE = new Color(139, 114, 190);
	public static final Color MIDDLE_GREEN = new Color(77, 140, 87);
	public static final Color MIDDLE_GREEN_YELLOW = new Color(172, 191, 96);
	public static final Color MIDDLE_GREY = new Color(139, 134, 128);
	public static final Color MIDDLE_PURPLE = new Color(217, 130, 181);
	public static final Color MIDDLE_RED = new Color(229, 142, 115);
	public static final Color MIDDLE_RED_PURPLE = new Color(165, 83, 83);
	public static final Color MIDDLE_YELLOW = new Color(255, 235, 0);
	public static final Color MIDDLE_YELLOW_RED = new Color(236, 177, 118);
	public static final Color MIDNIGHT = new Color(112, 38, 112);
	public static final Color MIDNIGHT_BLUE = new Color(25, 25, 112);
	public static final Color MIDNIGHT_GREEN = new Color(0, 73, 83);
	public static final Color MIKADO_YELLOW = new Color(255, 196, 12);
	public static final Color MIMI_PINK = new Color(255, 218, 233);
	public static final Color MINDARO = new Color(227, 249, 136);
	public static final Color MING = new Color(54, 116, 125);
	public static final Color MINION_YELLOW = new Color(245, 224, 80);
	public static final Color MINT = new Color(62, 180, 137);
	public static final Color MINT_CREAM = new Color(245, 255, 250);
	public static final Color MINT_GREEN = new Color(152, 255, 152);
	public static final Color MISTY_MOSS = new Color(187, 180, 119);
	public static final Color MISTY_ROSE = new Color(255, 228, 225);
	public static final Color MOCCASIN = new Color(255, 228, 181);
	public static final Color MODE_BEIGE = new Color(150, 113, 23);
	public static final Color MONA_LISA = new Color(255, 148, 142);
	public static final Color MORNING_BLUE = new Color(141, 163, 153);
	public static final Color MOSS_GREEN = new Color(138, 154, 91);
	public static final Color MOUNTAIN_MEADOW = new Color(48, 186, 143);
	public static final Color MOUNTBATTEN_PINK = new Color(153, 122, 141);
	public static final Color MULBERRY = new Color(197, 75, 140);
	public static final Color MUSTARD = new Color(255, 219, 88);
	public static final Color MYRTLE_GREEN = new Color(49, 120, 115);
	public static final Color MYSTIC = new Color(214, 82, 130);
	public static final Color MYSTIC_MAROON = new Color(173, 67, 121);
	public static final Color NADESHIKO_PINK = new Color(246, 173, 198);
	public static final Color NAPLES_YELLOW = new Color(250, 218, 94);
	public static final Color NAVAJO_WHITE = new Color(255, 222, 173);
	public static final Color NAVY_BLUE = new Color(0, 0, 128);
	public static final Color NEON_BLUE = new Color(70, 102, 255);
	public static final Color NEON_FUCHSIA = new Color(254, 65, 100);
	public static final Color NEON_GREEN = new Color(57, 255, 20);
	public static final Color NEW_CAR = new Color(33, 79, 198);
	public static final Color NEW_YORK_PINK = new Color(215, 131, 127);
	public static final Color NICKEL = new Color(114, 116, 114);
	public static final Color NON_PHOTO_BLUE = new Color(164, 221, 237);
	public static final Color NYANZA = new Color(233, 255, 219);
	public static final Color OU_CRIMSON_RED = new Color(132, 22, 23);
	public static final Color OCHRE = new Color(204, 119, 34);
	public static final Color OLD_BURGUNDY = new Color(67, 48, 46);
	public static final Color OLD_GOLD = new Color(207, 181, 59);
	public static final Color OLD_LACE = new Color(253, 245, 230);
	public static final Color OLD_LAVENDER = new Color(121, 104, 120);
	public static final Color OLD_MAUVE = new Color(103, 49, 71);
	public static final Color OLD_ROSE = new Color(192, 128, 129);
	public static final Color OLD_SILVER = new Color(132, 132, 130);
	public static final Color OLIVE = new Color(128, 128, 0);
	public static final Color OLIVE_DRAB_7 = new Color(60, 52, 31);
	public static final Color OLIVE_DRAB = new Color(107, 142, 35);
	public static final Color OLIVE_GREEN = new Color(181, 179, 92);
	public static final Color OLIVINE = new Color(154, 185, 115);
	public static final Color ONYX = new Color(53, 56, 57);
	public static final Color OPAL = new Color(168, 195, 188);
	public static final Color OPERA_MAUVE = new Color(183, 132, 167);
	public static final Color ORANGE = new Color(255, 127, 0);
	public static final Color ORANGE_JUICE = new Color(255, 165, 0);
	public static final Color ORANGE_PEEL = new Color(255, 159, 0);
	public static final Color ORANGE_SODA = new Color(250, 91, 61);
	public static final Color ORANGE_RED = new Color(255, 104, 31);
	public static final Color ORANGE_YELLOW = new Color(245, 189, 31);
	public static final Color ORCHID = new Color(218, 112, 214);
	public static final Color ORCHID_PINK = new Color(242, 189, 205);
	public static final Color OUTER_SPACE = new Color(45, 56, 58);
	public static final Color OUTRAGEOUS_ORANGE = new Color(255, 110, 74);
	public static final Color OXBLOOD = new Color(74, 0, 0);
	public static final Color OXFORD_BLUE = new Color(0, 33, 71);
	public static final Color PACIFIC_BLUE = new Color(28, 169, 201);
	public static final Color PAKISTAN_GREEN = new Color(0, 102, 0);
	public static final Color PALATINATE_PURPLE = new Color(104, 40, 96);
	public static final Color PALE_DOGWOOD = new Color(237, 122, 155);
	public static final Color PALE_AQUA = new Color(190, 211, 229);
	public static final Color PALE_CERULEAN = new Color(155, 196, 226);
	public static final Color PALE_PINK = new Color(250, 218, 221);
	public static final Color PALE_PURPLE = new Color(250, 230, 250);
	public static final Color PALE_SPRING_BUD = new Color(236, 235, 189);
	public static final Color PANSY_PURPLE = new Color(120, 24, 74);
	public static final Color PAOLO_VERONESE_GREEN = new Color(0, 155, 125);
	public static final Color PAPAYA_WHIP = new Color(255, 239, 213);
	public static final Color PARADISE_PINK = new Color(230, 62, 98);
	public static final Color PARCHMENT = new Color(241, 233, 210);
	public static final Color PARIS_GREEN = new Color(80, 200, 120);
	public static final Color PASTEL_PINK = new Color(222, 165, 164);
	public static final Color PATRIARCH = new Color(128, 0, 128);
	public static final Color PAUA = new Color(31, 0, 94);
	public static final Color PAYNES_GREY = new Color(83, 104, 120);
	public static final Color PEACH = new Color(255, 229, 180);
	public static final Color PEACH_PUFF = new Color(255, 218, 185);
	public static final Color PEAR = new Color(209, 226, 49);
	public static final Color PEARLY_PURPLE = new Color(183, 104, 162);
	public static final Color PERIWINKLE = new Color(204, 204, 255);
	public static final Color PERMANENT_GERANIUM_LAKE = new Color(225, 44, 44);
	public static final Color PERSIAN_BLUE = new Color(28, 57, 187);
	public static final Color PERSIAN_GREEN = new Color(0, 166, 147);
	public static final Color PERSIAN_INDIGO = new Color(50, 18, 122);
	public static final Color PERSIAN_ORANGE = new Color(217, 144, 88);
	public static final Color PERSIAN_PINK = new Color(247, 127, 190);
	public static final Color PERSIAN_PLUM = new Color(112, 28, 28);
	public static final Color PERSIAN_RED = new Color(204, 51, 51);
	public static final Color PERSIAN_ROSE = new Color(254, 40, 162);
	public static final Color PERSIMMON = new Color(236, 88, 0);
	public static final Color PEWTER_BLUE = new Color(139, 168, 183);
	public static final Color PHLOX = new Color(223, 0, 255);
	public static final Color PHTHALO_BLUE = new Color(0, 15, 137);
	public static final Color PHTHALO_GREEN = new Color(18, 53, 36);
	public static final Color PICOTEE_BLUE = new Color(46, 39, 135);
	public static final Color PICTORIAL_CARMINE = new Color(195, 11, 78);
	public static final Color PIGGY_PINK = new Color(253, 221, 230);
	public static final Color PINE_GREEN = new Color(1, 121, 111);
	public static final Color PINK = new Color(255, 192, 203);
	public static final Color PINK_SHERBET = new Color(247, 143, 167);
	public static final Color PINK_LACE = new Color(255, 221, 244);
	public static final Color PINK_LAVENDER = new Color(216, 178, 209);
	public static final Color PISTACHIO = new Color(147, 197, 114);
	public static final Color PLATINUM = new Color(229, 228, 226);
	public static final Color PLUM = new Color(142, 69, 133);
	public static final Color PLUMP_PURPLE = new Color(89, 70, 178);
	public static final Color POLISHED_PINE = new Color(93, 164, 147);
	public static final Color POMP_AND_POWER = new Color(134, 96, 142);
	public static final Color POPSTAR = new Color(190, 79, 98);
	public static final Color PORTLAND_ORANGE = new Color(255, 90, 54);
	public static final Color POWDER_BLUE = new Color(176, 224, 230);
	public static final Color PRAIRIE_GOLD = new Color(225, 202, 122);
	public static final Color PRINCETON_ORANGE = new Color(245, 128, 37);
	public static final Color PRUNE = new Color(112, 28, 28);
	public static final Color PRUSSIAN_BLUE = new Color(0, 49, 83);
	public static final Color PSYCHEDELIC_PURPLE = new Color(223, 0, 255);
	public static final Color PUCE = new Color(204, 136, 153);
	public static final Color PULLMAN_BROWN = new Color(100, 65, 23);
	public static final Color PUMPKIN = new Color(255, 117, 24);
	public static final Color PURPLE = new Color(106, 13, 173);
	public static final Color PURPLE_PLUM = new Color(156, 81, 182);
	public static final Color PURPLE_MOUNTAIN_MAJESTY = new Color(150, 120, 182);
	public static final Color PURPLE_NAVY = new Color(78, 81, 128);
	public static final Color PURPLE_PIZZAZZ = new Color(254, 78, 218);
	public static final Color QUEEN_BLUE = new Color(67, 107, 149);
	public static final Color QUEEN_PINK = new Color(232, 204, 215);
	public static final Color QUICK_SILVER = new Color(166, 166, 166);
	public static final Color QUINACRIDONE_MAGENTA = new Color(142, 58, 89);
	public static final Color RADICAL_RED = new Color(255, 53, 94);
	public static final Color RAISIN_BLACK = new Color(36, 33, 36);
	public static final Color RAJAH = new Color(251, 171, 96);
	public static final Color RASPBERRY = new Color(227, 11, 93);
	public static final Color RASPBERRY_GLACÉ = new Color(145, 95, 109);
	public static final Color RASPBERRY_ROSE = new Color(179, 68, 108);
	public static final Color RAW_SIENNA = new Color(214, 138, 89);
	public static final Color RAW_UMBER = new Color(130, 102, 68);
	public static final Color RAZZLE_DAZZLE_ROSE = new Color(255, 51, 204);
	public static final Color RAZZMATAZZ = new Color(227, 37, 107);
	public static final Color RAZZMIC_BERRY = new Color(141, 78, 133);
	public static final Color REBECCA_PURPLE = new Color(102, 51, 153);
	public static final Color RED = new Color(255, 0, 0);
	public static final Color RED_SALSA = new Color(253, 58, 74);
	public static final Color RED_OCHRE = new Color(145, 56, 49);
	public static final Color RED_ORANGE = new Color(255, 83, 73);
	public static final Color RED_PURPLE = new Color(228, 0, 120);
	public static final Color RED_VIOLET = new Color(199, 21, 133);
	public static final Color REDWOOD = new Color(164, 90, 82);
	public static final Color RESOLUTION_BLUE = new Color(0, 35, 135);
	public static final Color RHYTHM = new Color(119, 118, 150);
	public static final Color RICH_BLACK = new Color(0, 64, 64);
	public static final Color RIFLE_GREEN = new Color(68, 76, 56);
	public static final Color ROBIN_EGG_BLUE = new Color(0, 204, 204);
	public static final Color ROCKET_METALLIC = new Color(138, 127, 128);
	public static final Color ROJO_SPANISH_RED = new Color(169, 17, 1);
	public static final Color ROMAN_SILVER = new Color(131, 137, 150);
	public static final Color ROSE = new Color(255, 0, 127);
	public static final Color ROSE_DUST = new Color(158, 94, 111);
	public static final Color ROSE_POMPADOUR = new Color(237, 122, 155);
	public static final Color ROSE_BONBON = new Color(249, 66, 158);
	public static final Color ROSE_EBONY = new Color(103, 72, 70);
	public static final Color ROSE_MADDER = new Color(227, 38, 54);
	public static final Color ROSE_PINK = new Color(255, 102, 204);
	public static final Color ROSE_RED = new Color(194, 30, 86);
	public static final Color ROSE_TAUPE = new Color(144, 93, 93);
	public static final Color ROSE_VALE = new Color(171, 78, 82);
	public static final Color ROSEWOOD = new Color(101, 0, 11);
	public static final Color ROSSO_CORSA = new Color(212, 0, 0);
	public static final Color ROSY_BROWN = new Color(188, 143, 143);
	public static final Color ROYAL_BLUE = new Color(0, 35, 102);
	public static final Color ROYAL_PURPLE = new Color(120, 81, 169);
	public static final Color ROYAL_YELLOW = new Color(250, 218, 94);
	public static final Color RUBER = new Color(206, 70, 118);
	public static final Color RUBINE_RED = new Color(209, 0, 86);
	public static final Color RUBY = new Color(224, 17, 95);
	public static final Color RUBY_RED = new Color(155, 17, 30);
	public static final Color RUFOUS = new Color(168, 28, 7);
	public static final Color RUSSET = new Color(128, 70, 27);
	public static final Color RUSSIAN_GREEN = new Color(103, 146, 103);
	public static final Color RUSSIAN_VIOLET = new Color(50, 23, 77);
	public static final Color RUST = new Color(183, 65, 14);
	public static final Color RUSTY_RED = new Color(218, 44, 67);
	public static final Color SACRAMENTO_STATE_GREEN = new Color(4, 57, 39);
	public static final Color SADDLE_BROWN = new Color(139, 69, 19);
	public static final Color SAFETY_ORANGE = new Color(255, 120, 0);
	public static final Color SAFETY_YELLOW = new Color(238, 210, 2);
	public static final Color SAFFRON = new Color(244, 196, 48);
	public static final Color SAGE = new Color(188, 184, 138);
	public static final Color SALMON = new Color(250, 128, 114);
	public static final Color SALMON_PINK = new Color(255, 145, 164);
	public static final Color SAND = new Color(194, 178, 128);
	public static final Color SAND_DUNE = new Color(150, 113, 23);
	public static final Color SANDY_BROWN = new Color(244, 164, 96);
	public static final Color SAP_GREEN = new Color(80, 125, 42);
	public static final Color SAPPHIRE = new Color(15, 82, 186);
	public static final Color SAPPHIRE_BLUE = new Color(0, 103, 165);
	public static final Color SATIN_SHEEN_GOLD = new Color(203, 161, 53);
	public static final Color SCARLET = new Color(255, 36, 0);
	public static final Color SCHAUSS_PINK = new Color(255, 145, 175);
	public static final Color SCHOOL_BUS_YELLOW = new Color(255, 216, 0);
	public static final Color SCREAMIN_GREEN = new Color(102, 255, 102);
	public static final Color SEA_GREEN = new Color(46, 139, 87);
	public static final Color SEAL_BROWN = new Color(89, 38, 11);
	public static final Color SEANCE = new Color(97, 32, 134);
	public static final Color SEASHELL = new Color(255, 245, 238);
	public static final Color SECRET = new Color(118, 67, 116);
	public static final Color SELECTIVE_YELLOW = new Color(255, 186, 0);
	public static final Color SEPIA = new Color(112, 66, 20);
	public static final Color SHADOW = new Color(138, 121, 93);
	public static final Color SHADOW_BLUE = new Color(119, 139, 165);
	public static final Color SHAMROCK_GREEN = new Color(0, 158, 96);
	public static final Color SHEEN_GREEN = new Color(143, 212, 0);
	public static final Color SHIMMERING_BLUSH = new Color(217, 134, 149);
	public static final Color SHINY_SHAMROCK = new Color(95, 167, 120);
	public static final Color SHOCKING_PINK = new Color(252, 15, 192);
	public static final Color SIENNA = new Color(136, 45, 23);
	public static final Color SILVER = new Color(192, 192, 192);
	public static final Color SILVER_CHALICE = new Color(172, 172, 172);
	public static final Color SILVER_PINK = new Color(196, 174, 173);
	public static final Color SILVER_SAND = new Color(191, 193, 194);
	public static final Color SINOPIA = new Color(203, 65, 11);
	public static final Color SIZZLING_RED = new Color(255, 56, 85);
	public static final Color SIZZLING_SUNRISE = new Color(255, 219, 0);
	public static final Color SKOBELOFF = new Color(0, 116, 116);
	public static final Color SKY_BLUE = new Color(135, 206, 235);
	public static final Color SKY_MAGENTA = new Color(207, 113, 175);
	public static final Color SLATE_BLUE = new Color(106, 90, 205);
	public static final Color SLATE_GRAY = new Color(112, 128, 144);
	public static final Color SLIMY_GREEN = new Color(41, 150, 23);
	public static final Color SMITTEN = new Color(200, 65, 134);
	public static final Color SMOKY_BLACK = new Color(16, 12, 8);
	public static final Color SNOW = new Color(255, 250, 250);
	public static final Color SOLID_PINK = new Color(137, 56, 67);
	public static final Color SONIC_SILVER = new Color(117, 117, 117);
	public static final Color SPACE_CADET = new Color(29, 41, 81);
	public static final Color SPANISH_BISTRE = new Color(128, 117, 50);
	public static final Color SPANISH_BLUE = new Color(0, 112, 184);
	public static final Color SPANISH_CARMINE = new Color(209, 0, 71);
	public static final Color SPANISH_GRAY = new Color(152, 152, 152);
	public static final Color SPANISH_GREEN = new Color(0, 145, 80);
	public static final Color SPANISH_ORANGE = new Color(232, 97, 0);
	public static final Color SPANISH_PINK = new Color(247, 191, 190);
	public static final Color SPANISH_RED = new Color(230, 0, 38);
	public static final Color SPANISH_SKY_BLUE = new Color(0, 255, 254);
	public static final Color SPANISH_VIOLET = new Color(76, 40, 130);
	public static final Color SPANISH_VIRIDIAN = new Color(0, 127, 92);
	public static final Color SPRING_FROST = new Color(135, 255, 42);
	public static final Color SPRING_BUD = new Color(167, 252, 0);
	public static final Color SPRING_GREEN = new Color(0, 255, 127);
	public static final Color ST_PATRICKS_BLUE = new Color(35, 41, 122);
	public static final Color STAR_COMMAND_BLUE = new Color(0, 123, 184);
	public static final Color STEEL_BLUE = new Color(70, 130, 180);
	public static final Color STEEL_PINK = new Color(204, 51, 204);
	public static final Color STIL_DE_GRAIN_YELLOW = new Color(250, 218, 94);
	public static final Color STRAW = new Color(228, 217, 111);
	public static final Color STRAWBERRY = new Color(250, 80, 83);
	public static final Color STRAWBERRY_BLONDE = new Color(255, 147, 97);
	public static final Color STRONG_LIME_GREEN = new Color(51, 204, 51);
	public static final Color SUGAR_PLUM = new Color(145, 78, 117);
	public static final Color SUNGLOW = new Color(255, 204, 51);
	public static final Color SUNRAY = new Color(227, 171, 87);
	public static final Color SUNSET = new Color(250, 214, 165);
	public static final Color SUPER_PINK = new Color(207, 107, 169);
	public static final Color SWEET_BROWN = new Color(168, 55, 49);
	public static final Color SYRACUSE_ORANGE = new Color(212, 69, 0);
	public static final Color TAN = new Color(210, 180, 140);
	public static final Color TANGERINE = new Color(242, 133, 0);
	public static final Color TANGO_PINK = new Color(228, 113, 122);
	public static final Color TART_ORANGE = new Color(251, 77, 70);
	public static final Color TAUPE = new Color(72, 60, 50);
	public static final Color TAUPE_GRAY = new Color(139, 133, 137);
	public static final Color TEA_GREEN = new Color(208, 240, 192);
	public static final Color TEA_ROSE = new Color(244, 194, 194);
	public static final Color TEAL = new Color(0, 128, 128);
	public static final Color TEAL_BLUE = new Color(54, 117, 136);
	public static final Color TECHNOBOTANICA = new Color(0, 255, 191);
	public static final Color TELEMAGENTA = new Color(207, 52, 118);
	public static final Color TENNÉ = new Color(205, 87, 0);
	public static final Color TERRA_COTTA = new Color(226, 114, 91);
	public static final Color THISTLE = new Color(216, 191, 216);
	public static final Color THULIAN_PINK = new Color(222, 111, 161);
	public static final Color TICKLE_ME_PINK = new Color(252, 137, 172);
	public static final Color TIFFANY_BLUE = new Color(10, 186, 181);
	public static final Color TIMBERWOLF = new Color(219, 215, 210);
	public static final Color TITANIUM_YELLOW = new Color(238, 230, 0);
	public static final Color TOMATO = new Color(255, 99, 71);
	public static final Color TOURMALINE = new Color(134, 161, 169);
	public static final Color TROPICAL_RAINFOREST = new Color(0, 117, 94);
	public static final Color TRUE_BLUE = new Color(45, 104, 196);
	public static final Color TRYPAN_BLUE = new Color(28, 5, 179);
	public static final Color TUFTS_BLUE = new Color(62, 142, 222);
	public static final Color TUMBLEWEED = new Color(222, 170, 136);
	public static final Color TURQUOISE = new Color(64, 224, 208);
	public static final Color TURQUOISE_BLUE = new Color(0, 255, 239);
	public static final Color TURQUOISE_GREEN = new Color(160, 214, 180);
	public static final Color TURTLE_GREEN = new Color(138, 154, 91);
	public static final Color TUSCAN = new Color(250, 214, 165);
	public static final Color TUSCAN_BROWN = new Color(111, 78, 55);
	public static final Color TUSCAN_RED = new Color(124, 72, 72);
	public static final Color TUSCAN_TAN = new Color(166, 123, 91);
	public static final Color TUSCANY = new Color(192, 153, 153);
	public static final Color TWILIGHT_LAVENDER = new Color(138, 73, 107);
	public static final Color TYRIAN_PURPLE = new Color(102, 2, 60);
	public static final Color UA_BLUE = new Color(0, 51, 170);
	public static final Color UA_RED = new Color(217, 0, 76);
	public static final Color UP_FOREST_GREEN = new Color(1, 68, 33);
	public static final Color UP_MAROON = new Color(123, 17, 19);
	public static final Color USAFA_BLUE = new Color(0, 79, 152);
	public static final Color ULTRA_PINK = new Color(255, 111, 255);
	public static final Color ULTRA_RED = new Color(252, 108, 133);
	public static final Color ULTRAMARINE = new Color(63, 0, 255);
	public static final Color ULTRAMARINE_BLUE = new Color(65, 102, 245);
	public static final Color UMBER = new Color(99, 81, 71);
	public static final Color UNBLEACHED_SILK = new Color(255, 221, 202);
	public static final Color UNITED_NATIONS_BLUE = new Color(0, 158, 219);
	public static final Color UNIVERSITY_OF_PENNSYLVANIA_RED = new Color(165, 0, 33);
	public static final Color UNMELLOW_YELLOW = new Color(255, 255, 102);
	public static final Color UPSDELL_RED = new Color(174, 32, 41);
	public static final Color URANIAN_BLUE = new Color(175, 219, 245);
	public static final Color VAN_DYKE_BROWN = new Color(102, 66, 40);
	public static final Color VANILLA = new Color(243, 229, 171);
	public static final Color VANILLA_ICE = new Color(243, 143, 169);
	public static final Color VEGAS_GOLD = new Color(197, 179, 88);
	public static final Color VENETIAN_RED = new Color(200, 8, 21);
	public static final Color VERDIGRIS = new Color(67, 179, 174);
	public static final Color VERMILION = new Color(227, 66, 52);
	public static final Color VERONICA = new Color(160, 32, 240);
	public static final Color VIOLET = new Color(143, 0, 255);
	public static final Color VIOLET_BLUE = new Color(50, 74, 178);
	public static final Color VIOLET_RED = new Color(247, 83, 148);
	public static final Color VIRIDIAN = new Color(64, 130, 109);
	public static final Color VIRIDIAN_GREEN = new Color(0, 150, 152);
	public static final Color VIVID_BURGUNDY = new Color(159, 29, 53);
	public static final Color VIVID_SKY_BLUE = new Color(0, 204, 255);
	public static final Color VIVID_TANGERINE = new Color(255, 160, 137);
	public static final Color VIVID_VIOLET = new Color(159, 0, 255);
	public static final Color VOLT = new Color(206, 255, 0);
	public static final Color WARM_BLACK = new Color(0, 66, 66);
	public static final Color WEEZY_BLUE = new Color(24, 155, 204);
	public static final Color WHEAT = new Color(245, 222, 179);
	public static final Color WHITE = new Color(255, 255, 255);
	public static final Color WILD_STRAWBERRY = new Color(255, 67, 164);
	public static final Color WILD_BLUE_YONDER = new Color(162, 173, 208);
	public static final Color WILD_ORCHID = new Color(212, 112, 162);
	public static final Color WILD_WATERMELON = new Color(252, 108, 133);
	public static final Color WINDSOR_TAN = new Color(167, 85, 2);
	public static final Color WINE = new Color(114, 47, 55);
	public static final Color WINE_DREGS = new Color(103, 49, 71);
	public static final Color WINTER_SKY = new Color(255, 0, 124);
	public static final Color WINTERGREEN_DREAM = new Color(86, 136, 125);
	public static final Color WISTERIA = new Color(201, 160, 220);
	public static final Color WOOD_BROWN = new Color(193, 154, 107);
	public static final Color XANADU = new Color(115, 134, 120);
	public static final Color XANTHIC = new Color(238, 237, 9);
	public static final Color XANTHOUS = new Color(241, 180, 47);
	public static final Color YINMN_BLUE = new Color(46, 80, 144);
	public static final Color YALE_BLUE = new Color(0, 53, 107);
	public static final Color YELLOW = new Color(255, 255, 0);
	public static final Color YELLOW_ORANGE = new Color(255, 174, 66);
	public static final Color YELLOW_SUNSHINE = new Color(255, 247, 0);
	public static final Color YELLOW_GREEN = new Color(154, 205, 50);
	public static final Color ZAFFRE = new Color(0, 20, 168);
	public static final Color ZINNWALDITE_BROWN = new Color(44, 22, 8);
	public static final Color ZOMP = new Color(57, 167, 142);

	public static final Color AO = new Color(0, 128, 0);
	public static final Color BRIGHT_CERULEAN = new Color(0, 183, 211);
	public static final Color CINDER = new Color(14, 14, 24);
	public static final Color CRYSTAL_BLUE = new Color(92, 179, 255);
	public static final Color CRYSTAL_GREEN = new Color(160, 215, 122);
	public static final Color DARK_BLUE = new Color(0, 3, 91);
	public static final Color FORSYTHIA = new Color(255, 200, 0);
	public static final Color HOT_PEPPER_GREEN = new Color(89, 128, 57);
	public static final Color LAVENDER_MIST = new Color(230, 230, 250);
	public static final Color LIGHT_SLATE_BLUE = new Color(106, 93, 255);
	public static final Color MYRTLE = new Color(33, 66, 30);
	public static final Color SWAMP_MOSS = new Color(105, 131, 57);

	static {
		registerColor("ABSOLUTE_ZERO", ABSOLUTE_ZERO);
		registerColor("ACID_GREEN", ACID_GREEN);
		registerColor("AERO", AERO);
		registerColor("AFRICAN_VIOLET", AFRICAN_VIOLET);
		registerColor("AIR_SUPERIORITY_BLUE", AIR_SUPERIORITY_BLUE);
		registerColor("ALICE_BLUE", ALICE_BLUE);
		registerColor("ALIZARIN", ALIZARIN);
		registerColor("ALLOY_ORANGE", ALLOY_ORANGE);
		registerColor("ALMOND", ALMOND);
		registerColor("AMARANTH_DEEP_PURPLE", AMARANTH_DEEP_PURPLE);
		registerColor("AMARANTH_PINK", AMARANTH_PINK);
		registerColor("AMARANTH_PURPLE", AMARANTH_PURPLE);
		registerColor("AMAZON", AMAZON);
		registerColor("AMBER", AMBER);
		registerColor("AMETHYST", AMETHYST);
		registerColor("ANDROID_GREEN", ANDROID_GREEN);
		registerColor("ANTIQUE_BRASS", ANTIQUE_BRASS);
		registerColor("ANTIQUE_BRONZE", ANTIQUE_BRONZE);
		registerColor("ANTIQUE_FUCHSIA", ANTIQUE_FUCHSIA);
		registerColor("ANTIQUE_RUBY", ANTIQUE_RUBY);
		registerColor("ANTIQUE_WHITE", ANTIQUE_WHITE);
		registerColor("APRICOT", APRICOT);
		registerColor("AQUA", AQUA);
		registerColor("AQUAMARINE", AQUAMARINE);
		registerColor("ARCTIC_LIME", ARCTIC_LIME);
		registerColor("ARTICHOKE_GREEN", ARTICHOKE_GREEN);
		registerColor("ARYLIDE_YELLOW", ARYLIDE_YELLOW);
		registerColor("ASH_GRAY", ASH_GRAY);
		registerColor("ATOMIC_TANGERINE", ATOMIC_TANGERINE);
		registerColor("AUREOLIN", AUREOLIN);
		registerColor("AZURE", AZURE);
		registerColor("BDAZZLED_BLUE", BDAZZLED_BLUE);
		registerColor("BABY_BLUE", BABY_BLUE);
		registerColor("BABY_BLUE_EYES", BABY_BLUE_EYES);
		registerColor("BABY_PINK", BABY_PINK);
		registerColor("BABY_POWDER", BABY_POWDER);
		registerColor("BAKER_MILLER_PINK", BAKER_MILLER_PINK);
		registerColor("BANANA_MANIA", BANANA_MANIA);
		registerColor("BARBIE_PINK", BARBIE_PINK);
		registerColor("BARN_RED", BARN_RED);
		registerColor("BATTLESHIP_GREY", BATTLESHIP_GREY);
		registerColor("BEAU_BLUE", BEAU_BLUE);
		registerColor("BEAVER", BEAVER);
		registerColor("BEIGE", BEIGE);
		registerColor("BIG_DIP_ORUBY", BIG_DIP_ORUBY);
		registerColor("BISQUE", BISQUE);
		registerColor("BISTRE", BISTRE);
		registerColor("BISTRE_BROWN", BISTRE_BROWN);
		registerColor("BITTER_LEMON", BITTER_LEMON);
		registerColor("BLACK", BLACK);
		registerColor("BLACK_SHADOWS", BLACK_SHADOWS);
		registerColor("BLACK_BEAN", BLACK_BEAN);
		registerColor("BLACK_CORAL", BLACK_CORAL);
		registerColor("BLACK_OLIVE", BLACK_OLIVE);
		registerColor("BLANCHED_ALMOND", BLANCHED_ALMOND);
		registerColor("BLAST_OFF_BRONZE", BLAST_OFF_BRONZE);
		registerColor("BLEU_DE_FRANCE", BLEU_DE_FRANCE);
		registerColor("BLIZZARD_BLUE", BLIZZARD_BLUE);
		registerColor("BLOOD_RED", BLOOD_RED);
		registerColor("BLUE", BLUE);
		registerColor("BLUE_BELL", BLUE_BELL);
		registerColor("BLUE_JEANS", BLUE_JEANS);
		registerColor("BLUE_SAPPHIRE", BLUE_SAPPHIRE);
		registerColor("BLUE_YONDER", BLUE_YONDER);
		registerColor("BLUE_GRAY", BLUE_GRAY);
		registerColor("BLUE_VIOLET", BLUE_VIOLET);
		registerColor("BLUETIFUL", BLUETIFUL);
		registerColor("BLUSH", BLUSH);
		registerColor("BOLE", BOLE);
		registerColor("BONE", BONE);
		registerColor("BRICK_RED", BRICK_RED);
		registerColor("BRIGHT_LILAC", BRIGHT_LILAC);
		registerColor("BRIGHT_YELLOW", BRIGHT_YELLOW);
		registerColor("BRITISH_RACING_GREEN", BRITISH_RACING_GREEN);
		registerColor("BRONZE", BRONZE);
		registerColor("BROWN", BROWN);
		registerColor("BROWN_SUGAR", BROWN_SUGAR);
		registerColor("BUD_GREEN", BUD_GREEN);
		registerColor("BUFF", BUFF);
		registerColor("BURGUNDY", BURGUNDY);
		registerColor("BURLYWOOD", BURLYWOOD);
		registerColor("BURNISHED_BROWN", BURNISHED_BROWN);
		registerColor("BURNT_ORANGE", BURNT_ORANGE);
		registerColor("BURNT_SIENNA", BURNT_SIENNA);
		registerColor("BURNT_UMBER", BURNT_UMBER);
		registerColor("BYZANTINE", BYZANTINE);
		registerColor("BYZANTIUM", BYZANTIUM);
		registerColor("CADET_BLUE", CADET_BLUE);
		registerColor("CADET_GREY", CADET_GREY);
		registerColor("CADMIUM_GREEN", CADMIUM_GREEN);
		registerColor("CADMIUM_ORANGE", CADMIUM_ORANGE);
		registerColor("CAFÉ_AU_LAIT", CAFÉ_AU_LAIT);
		registerColor("CAFÉ_NOIR", CAFÉ_NOIR);
		registerColor("CAMBRIDGE_BLUE", CAMBRIDGE_BLUE);
		registerColor("CAMEL", CAMEL);
		registerColor("CAMEO_PINK", CAMEO_PINK);
		registerColor("CANARY", CANARY);
		registerColor("CANARY_YELLOW", CANARY_YELLOW);
		registerColor("CANDY_PINK", CANDY_PINK);
		registerColor("CARDINAL", CARDINAL);
		registerColor("CARIBBEAN_GREEN", CARIBBEAN_GREEN);
		registerColor("CARMINE", CARMINE);
		registerColor("CARNATION_PINK", CARNATION_PINK);
		registerColor("CARNELIAN", CARNELIAN);
		registerColor("CAROLINA_BLUE", CAROLINA_BLUE);
		registerColor("CARROT_ORANGE", CARROT_ORANGE);
		registerColor("CATAWBA", CATAWBA);
		registerColor("CEDAR_CHEST", CEDAR_CHEST);
		registerColor("CELADON", CELADON);
		registerColor("CELESTE", CELESTE);
		registerColor("CERISE", CERISE);
		registerColor("CERULEAN", CERULEAN);
		registerColor("CERULEAN_BLUE", CERULEAN_BLUE);
		registerColor("CERULEAN_FROST", CERULEAN_FROST);
		registerColor("CHAMPAGNE", CHAMPAGNE);
		registerColor("CHAMPAGNE_PINK", CHAMPAGNE_PINK);
		registerColor("CHARCOAL", CHARCOAL);
		registerColor("CHARM_PINK", CHARM_PINK);
		registerColor("CHARTREUSE", CHARTREUSE);
		registerColor("CHERRY_BLOSSOM_PINK", CHERRY_BLOSSOM_PINK);
		registerColor("CHESTNUT", CHESTNUT);
		registerColor("CHILI_RED", CHILI_RED);
		registerColor("CHINA_PINK", CHINA_PINK);
		registerColor("CHINESE_RED", CHINESE_RED);
		registerColor("CHINESE_VIOLET", CHINESE_VIOLET);
		registerColor("CHINESE_YELLOW", CHINESE_YELLOW);
		registerColor("CHOCOLATE", CHOCOLATE);
		registerColor("CINEREOUS", CINEREOUS);
		registerColor("CINNABAR", CINNABAR);
		registerColor("CINNAMON_SATIN", CINNAMON_SATIN);
		registerColor("CITRINE", CITRINE);
		registerColor("CITRON", CITRON);
		registerColor("CLARET", CLARET);
		registerColor("COFFEE", COFFEE);
		registerColor("COLUMBIA_BLUE", COLUMBIA_BLUE);
		registerColor("CONGO_PINK", CONGO_PINK);
		registerColor("COOL_GREY", COOL_GREY);
		registerColor("COPPER", COPPER);
		registerColor("COPPER_PENNY", COPPER_PENNY);
		registerColor("COPPER_RED", COPPER_RED);
		registerColor("COPPER_ROSE", COPPER_ROSE);
		registerColor("COQUELICOT", COQUELICOT);
		registerColor("CORAL", CORAL);
		registerColor("CORAL_PINK", CORAL_PINK);
		registerColor("CORDOVAN", CORDOVAN);
		registerColor("CORN", CORN);
		registerColor("CORNFLOWER_BLUE", CORNFLOWER_BLUE);
		registerColor("CORNSILK", CORNSILK);
		registerColor("COSMIC_COBALT", COSMIC_COBALT);
		registerColor("COSMIC_LATTE", COSMIC_LATTE);
		registerColor("COTTON_CANDY", COTTON_CANDY);
		registerColor("COYOTE_BROWN", COYOTE_BROWN);
		registerColor("CREAM", CREAM);
		registerColor("CRIMSON", CRIMSON);
		registerColor("CULTURED_PEARL", CULTURED_PEARL);
		registerColor("CYAN", CYAN);
		registerColor("CYBER_GRAPE", CYBER_GRAPE);
		registerColor("CYBER_YELLOW", CYBER_YELLOW);
		registerColor("CYCLAMEN", CYCLAMEN);
		registerColor("DANDELION", DANDELION);
		registerColor("DARK_BROWN", DARK_BROWN);
		registerColor("DARK_BYZANTIUM", DARK_BYZANTIUM);
		registerColor("DARK_CYAN", DARK_CYAN);
		registerColor("DARK_ELECTRIC_BLUE", DARK_ELECTRIC_BLUE);
		registerColor("DARK_GOLDENROD", DARK_GOLDENROD);
		registerColor("DARK_GREEN", DARK_GREEN);
		registerColor("DARK_JUNGLE_GREEN", DARK_JUNGLE_GREEN);
		registerColor("DARK_KHAKI", DARK_KHAKI);
		registerColor("DARK_LAVA", DARK_LAVA);
		registerColor("DARK_LIVER", DARK_LIVER);
		registerColor("DARK_MAGENTA", DARK_MAGENTA);
		registerColor("DARK_OLIVE_GREEN", DARK_OLIVE_GREEN);
		registerColor("DARK_ORANGE", DARK_ORANGE);
		registerColor("DARK_ORCHID", DARK_ORCHID);
		registerColor("DARK_PURPLE", DARK_PURPLE);
		registerColor("DARK_RED", DARK_RED);
		registerColor("DARK_SALMON", DARK_SALMON);
		registerColor("DARK_SEA_GREEN", DARK_SEA_GREEN);
		registerColor("DARK_SIENNA", DARK_SIENNA);
		registerColor("DARK_SKY_BLUE", DARK_SKY_BLUE);
		registerColor("DARK_SLATE_BLUE", DARK_SLATE_BLUE);
		registerColor("DARK_SLATE_GRAY", DARK_SLATE_GRAY);
		registerColor("DARK_SPRING_GREEN", DARK_SPRING_GREEN);
		registerColor("DARK_TURQUOISE", DARK_TURQUOISE);
		registerColor("DARK_VIOLET", DARK_VIOLET);
		registerColor("DAVYS_GREY", DAVYS_GREY);
		registerColor("DEEP_SPACE_SPARKLE", DEEP_SPACE_SPARKLE);
		registerColor("DEEP_CERISE", DEEP_CERISE);
		registerColor("DEEP_CHAMPAGNE", DEEP_CHAMPAGNE);
		registerColor("DEEP_CHESTNUT", DEEP_CHESTNUT);
		registerColor("DEEP_JUNGLE_GREEN", DEEP_JUNGLE_GREEN);
		registerColor("DEEP_PINK", DEEP_PINK);
		registerColor("DEEP_SAFFRON", DEEP_SAFFRON);
		registerColor("DEEP_SKY_BLUE", DEEP_SKY_BLUE);
		registerColor("DEEP_TAUPE", DEEP_TAUPE);
		registerColor("DENIM", DENIM);
		registerColor("DENIM_BLUE", DENIM_BLUE);
		registerColor("DESERT", DESERT);
		registerColor("DESERT_SAND", DESERT_SAND);
		registerColor("DIM_GRAY", DIM_GRAY);
		registerColor("DODGER_BLUE", DODGER_BLUE);
		registerColor("DRAB_DARK_BROWN", DRAB_DARK_BROWN);
		registerColor("DUKE_BLUE", DUKE_BLUE);
		registerColor("DUTCH_WHITE", DUTCH_WHITE);
		registerColor("EBONY", EBONY);
		registerColor("ECRU", ECRU);
		registerColor("EERIE_BLACK", EERIE_BLACK);
		registerColor("EGGPLANT", EGGPLANT);
		registerColor("EGGSHELL", EGGSHELL);
		registerColor("ELECTRIC_LIME", ELECTRIC_LIME);
		registerColor("ELECTRIC_PURPLE", ELECTRIC_PURPLE);
		registerColor("ELECTRIC_VIOLET", ELECTRIC_VIOLET);
		registerColor("EMERALD", EMERALD);
		registerColor("EMINENCE", EMINENCE);
		registerColor("ENGLISH_LAVENDER", ENGLISH_LAVENDER);
		registerColor("ENGLISH_RED", ENGLISH_RED);
		registerColor("ENGLISH_VERMILLION", ENGLISH_VERMILLION);
		registerColor("ENGLISH_VIOLET", ENGLISH_VIOLET);
		registerColor("ERIN", ERIN);
		registerColor("ETON_BLUE", ETON_BLUE);
		registerColor("FALLOW", FALLOW);
		registerColor("FALU_RED", FALU_RED);
		registerColor("FANDANGO", FANDANGO);
		registerColor("FANDANGO_PINK", FANDANGO_PINK);
		registerColor("FAWN", FAWN);
		registerColor("FERN_GREEN", FERN_GREEN);
		registerColor("FIELD_DRAB", FIELD_DRAB);
		registerColor("FIERY_ROSE", FIERY_ROSE);
		registerColor("FINN", FINN);
		registerColor("FIRE_ENGINE_RED", FIRE_ENGINE_RED);
		registerColor("FIREBRICK", FIREBRICK);
		registerColor("FLAME", FLAME);
		registerColor("FLAX", FLAX);
		registerColor("FLIRT", FLIRT);
		registerColor("FLORAL_WHITE", FLORAL_WHITE);
		registerColor("FOREST_GREEN", FOREST_GREEN);
		registerColor("FRENCH_BEIGE", FRENCH_BEIGE);
		registerColor("FRENCH_BISTRE", FRENCH_BISTRE);
		registerColor("FRENCH_BLUE", FRENCH_BLUE);
		registerColor("FRENCH_FUCHSIA", FRENCH_FUCHSIA);
		registerColor("FRENCH_LILAC", FRENCH_LILAC);
		registerColor("FRENCH_LIME", FRENCH_LIME);
		registerColor("FRENCH_MAUVE", FRENCH_MAUVE);
		registerColor("FRENCH_PINK", FRENCH_PINK);
		registerColor("FRENCH_RASPBERRY", FRENCH_RASPBERRY);
		registerColor("FRENCH_SKY_BLUE", FRENCH_SKY_BLUE);
		registerColor("FRENCH_VIOLET", FRENCH_VIOLET);
		registerColor("FROSTBITE", FROSTBITE);
		registerColor("FUCHSIA", FUCHSIA);
		registerColor("FULVOUS", FULVOUS);
		registerColor("FUZZY_WUZZY", FUZZY_WUZZY);
		registerColor("GO_GREEN", GO_GREEN);
		registerColor("GAINSBORO", GAINSBORO);
		registerColor("GAMBOGE", GAMBOGE);
		registerColor("GENERIC_VIRIDIAN", GENERIC_VIRIDIAN);
		registerColor("GHOST_WHITE", GHOST_WHITE);
		registerColor("GLAUCOUS", GLAUCOUS);
		registerColor("GLOSSY_GRAPE", GLOSSY_GRAPE);
		registerColor("GOLD", GOLD);
		registerColor("GOLD_FUSION", GOLD_FUSION);
		registerColor("GOLDEN_BROWN", GOLDEN_BROWN);
		registerColor("GOLDEN_POPPY", GOLDEN_POPPY);
		registerColor("GOLDEN_YELLOW", GOLDEN_YELLOW);
		registerColor("GOLDENROD", GOLDENROD);
		registerColor("GOTHAM_GREEN", GOTHAM_GREEN);
		registerColor("GRANITE_GRAY", GRANITE_GRAY);
		registerColor("GRANNY_SMITH_APPLE", GRANNY_SMITH_APPLE);
		registerColor("GRAY", GRAY);
		registerColor("GREEN", GREEN);
		registerColor("GREEN_LIZARD", GREEN_LIZARD);
		registerColor("GREEN_SHEEN", GREEN_SHEEN);
		registerColor("GREEN_BLUE", GREEN_BLUE);
		registerColor("GUNMETAL", GUNMETAL);
		registerColor("HANSA_YELLOW", HANSA_YELLOW);
		registerColor("HARLEQUIN", HARLEQUIN);
		registerColor("HARVEST_GOLD", HARVEST_GOLD);
		registerColor("HEAT_WAVE", HEAT_WAVE);
		registerColor("HELIOTROPE", HELIOTROPE);
		registerColor("HELIOTROPE_GRAY", HELIOTROPE_GRAY);
		registerColor("HOLLYWOOD_CERISE", HOLLYWOOD_CERISE);
		registerColor("HONOLULU_BLUE", HONOLULU_BLUE);
		registerColor("HOOKERS_GREEN", HOOKERS_GREEN);
		registerColor("HOT_MAGENTA", HOT_MAGENTA);
		registerColor("HOT_PINK", HOT_PINK);
		registerColor("HUNTER_GREEN", HUNTER_GREEN);
		registerColor("ICEBERG", ICEBERG);
		registerColor("ILLUMINATING_EMERALD", ILLUMINATING_EMERALD);
		registerColor("IMPERIAL_RED", IMPERIAL_RED);
		registerColor("INCHWORM", INCHWORM);
		registerColor("INDEPENDENCE", INDEPENDENCE);
		registerColor("INDIA_GREEN", INDIA_GREEN);
		registerColor("INDIAN_RED", INDIAN_RED);
		registerColor("INDIAN_YELLOW", INDIAN_YELLOW);
		registerColor("INDIGO", INDIGO);
		registerColor("INDIGO_DYE", INDIGO_DYE);
		registerColor("INTERNATIONAL_KLEIN_BLUE", INTERNATIONAL_KLEIN_BLUE);
		registerColor("INTERNATIONAL_ORANGE", INTERNATIONAL_ORANGE);
		registerColor("IRRESISTIBLE", IRRESISTIBLE);
		registerColor("ISABELLINE", ISABELLINE);
		registerColor("ITALIAN_SKY_BLUE", ITALIAN_SKY_BLUE);
		registerColor("IVORY", IVORY);
		registerColor("JAPANESE_CARMINE", JAPANESE_CARMINE);
		registerColor("JAPANESE_VIOLET", JAPANESE_VIOLET);
		registerColor("JASMINE", JASMINE);
		registerColor("JAZZBERRY_JAM", JAZZBERRY_JAM);
		registerColor("JET", JET);
		registerColor("JONQUIL", JONQUIL);
		registerColor("JUNE_BUD", JUNE_BUD);
		registerColor("JUNGLE_GREEN", JUNGLE_GREEN);
		registerColor("KSU_PURPLE", KSU_PURPLE);
		registerColor("KELLY_GREEN", KELLY_GREEN);
		registerColor("KEPPEL", KEPPEL);
		registerColor("KEY_LIME", KEY_LIME);
		registerColor("KHAKI", KHAKI);
		registerColor("KOBE", KOBE);
		registerColor("KOBI", KOBI);
		registerColor("KOBICHA", KOBICHA);
		registerColor("LANGUID_LAVENDER", LANGUID_LAVENDER);
		registerColor("LAPIS_LAZULI", LAPIS_LAZULI);
		registerColor("LASER_LEMON", LASER_LEMON);
		registerColor("LAUREL_GREEN", LAUREL_GREEN);
		registerColor("LAVA", LAVA);
		registerColor("LAVENDER", LAVENDER);
		registerColor("LAVENDER_BLUE", LAVENDER_BLUE);
		registerColor("LAVENDER_BLUSH", LAVENDER_BLUSH);
		registerColor("LAVENDER_GRAY", LAVENDER_GRAY);
		registerColor("LAWN_GREEN", LAWN_GREEN);
		registerColor("LEMON", LEMON);
		registerColor("LEMON_CHIFFON", LEMON_CHIFFON);
		registerColor("LEMON_CURRY", LEMON_CURRY);
		registerColor("LEMON_GLACIER", LEMON_GLACIER);
		registerColor("LEMON_MERINGUE", LEMON_MERINGUE);
		registerColor("LEMON_YELLOW", LEMON_YELLOW);
		registerColor("LIBERTY", LIBERTY);
		registerColor("LIGHT_FRENCH_BEIGE", LIGHT_FRENCH_BEIGE);
		registerColor("LIGHT_BLUE", LIGHT_BLUE);
		registerColor("LIGHT_CORAL", LIGHT_CORAL);
		registerColor("LIGHT_CORNFLOWER_BLUE", LIGHT_CORNFLOWER_BLUE);
		registerColor("LIGHT_CYAN", LIGHT_CYAN);
		registerColor("LIGHT_GOLDENROD_YELLOW", LIGHT_GOLDENROD_YELLOW);
		registerColor("LIGHT_GRAY", LIGHT_GRAY);
		registerColor("LIGHT_GREEN", LIGHT_GREEN);
		registerColor("LIGHT_ORANGE", LIGHT_ORANGE);
		registerColor("LIGHT_PERIWINKLE", LIGHT_PERIWINKLE);
		registerColor("LIGHT_PINK", LIGHT_PINK);
		registerColor("LIGHT_PURPLE", LIGHT_PURPLE);
		registerColor("LIGHT_SALMON", LIGHT_SALMON);
		registerColor("LIGHT_SEA_GREEN", LIGHT_SEA_GREEN);
		registerColor("LIGHT_SKY_BLUE", LIGHT_SKY_BLUE);
		registerColor("LIGHT_SLATE_GRAY", LIGHT_SLATE_GRAY);
		registerColor("LIGHT_STEEL_BLUE", LIGHT_STEEL_BLUE);
		registerColor("LIGHT_YELLOW", LIGHT_YELLOW);
		registerColor("LILAC", LILAC);
		registerColor("LILAC_LUSTER", LILAC_LUSTER);
		registerColor("LIME", LIME);
		registerColor("LIME_GREEN", LIME_GREEN);
		registerColor("LINCOLN_GREEN", LINCOLN_GREEN);
		registerColor("LINEN", LINEN);
		registerColor("LION", LION);
		registerColor("LISERAN_PURPLE", LISERAN_PURPLE);
		registerColor("LITTLE_BOY_BLUE", LITTLE_BOY_BLUE);
		registerColor("LIVER", LIVER);
		registerColor("LIVER_CHESTNUT", LIVER_CHESTNUT);
		registerColor("LIVID", LIVID);
		registerColor("MSU_GREEN", MSU_GREEN);
		registerColor("MACARONI_AND_CHEESE", MACARONI_AND_CHEESE);
		registerColor("MADDER_LAKE", MADDER_LAKE);
		registerColor("MAGENTA", MAGENTA);
		registerColor("MAGENTA_HAZE", MAGENTA_HAZE);
		registerColor("MAGIC_MINT", MAGIC_MINT);
		registerColor("MAGNOLIA", MAGNOLIA);
		registerColor("MAHOGANY", MAHOGANY);
		registerColor("MAIZE", MAIZE);
		registerColor("MAJORELLE_BLUE", MAJORELLE_BLUE);
		registerColor("MALACHITE", MALACHITE);
		registerColor("MANATEE", MANATEE);
		registerColor("MANDARIN", MANDARIN);
		registerColor("MANGO", MANGO);
		registerColor("MANGO_TANGO", MANGO_TANGO);
		registerColor("MANTIS", MANTIS);
		registerColor("MARDI_GRAS", MARDI_GRAS);
		registerColor("MARIGOLD", MARIGOLD);
		registerColor("MAROON", MAROON);
		registerColor("MAUVE", MAUVE);
		registerColor("MAUVE_TAUPE", MAUVE_TAUPE);
		registerColor("MAUVELOUS", MAUVELOUS);
		registerColor("MAXIMUM_BLUE", MAXIMUM_BLUE);
		registerColor("MAXIMUM_BLUE_GREEN", MAXIMUM_BLUE_GREEN);
		registerColor("MAXIMUM_BLUE_PURPLE", MAXIMUM_BLUE_PURPLE);
		registerColor("MAXIMUM_GREEN", MAXIMUM_GREEN);
		registerColor("MAXIMUM_GREEN_YELLOW", MAXIMUM_GREEN_YELLOW);
		registerColor("MAXIMUM_PURPLE", MAXIMUM_PURPLE);
		registerColor("MAXIMUM_RED", MAXIMUM_RED);
		registerColor("MAXIMUM_RED_PURPLE", MAXIMUM_RED_PURPLE);
		registerColor("MAXIMUM_YELLOW", MAXIMUM_YELLOW);
		registerColor("MAXIMUM_YELLOW_RED", MAXIMUM_YELLOW_RED);
		registerColor("MAY_GREEN", MAY_GREEN);
		registerColor("MAYA_BLUE", MAYA_BLUE);
		registerColor("MEDIUM_AQUAMARINE", MEDIUM_AQUAMARINE);
		registerColor("MEDIUM_BLUE", MEDIUM_BLUE);
		registerColor("MEDIUM_CANDY_APPLE_RED", MEDIUM_CANDY_APPLE_RED);
		registerColor("MEDIUM_CARMINE", MEDIUM_CARMINE);
		registerColor("MEDIUM_CHAMPAGNE", MEDIUM_CHAMPAGNE);
		registerColor("MEDIUM_ORCHID", MEDIUM_ORCHID);
		registerColor("MEDIUM_PURPLE", MEDIUM_PURPLE);
		registerColor("MEDIUM_SEA_GREEN", MEDIUM_SEA_GREEN);
		registerColor("MEDIUM_SLATE_BLUE", MEDIUM_SLATE_BLUE);
		registerColor("MEDIUM_SPRING_GREEN", MEDIUM_SPRING_GREEN);
		registerColor("MEDIUM_TURQUOISE", MEDIUM_TURQUOISE);
		registerColor("MEDIUM_VIOLET_RED", MEDIUM_VIOLET_RED);
		registerColor("MELLOW_APRICOT", MELLOW_APRICOT);
		registerColor("MELLOW_YELLOW", MELLOW_YELLOW);
		registerColor("MELON", MELON);
		registerColor("METALLIC_SEAWEED", METALLIC_SEAWEED);
		registerColor("METALLIC_SUNBURST", METALLIC_SUNBURST);
		registerColor("METALLIC_GOLD", METALLIC_GOLD);
		registerColor("MEXICAN_PINK", MEXICAN_PINK);
		registerColor("MIDDLE_BLUE", MIDDLE_BLUE);
		registerColor("MIDDLE_BLUE_GREEN", MIDDLE_BLUE_GREEN);
		registerColor("MIDDLE_BLUE_PURPLE", MIDDLE_BLUE_PURPLE);
		registerColor("MIDDLE_GREEN", MIDDLE_GREEN);
		registerColor("MIDDLE_GREEN_YELLOW", MIDDLE_GREEN_YELLOW);
		registerColor("MIDDLE_GREY", MIDDLE_GREY);
		registerColor("MIDDLE_PURPLE", MIDDLE_PURPLE);
		registerColor("MIDDLE_RED", MIDDLE_RED);
		registerColor("MIDDLE_RED_PURPLE", MIDDLE_RED_PURPLE);
		registerColor("MIDDLE_YELLOW", MIDDLE_YELLOW);
		registerColor("MIDDLE_YELLOW_RED", MIDDLE_YELLOW_RED);
		registerColor("MIDNIGHT", MIDNIGHT);
		registerColor("MIDNIGHT_BLUE", MIDNIGHT_BLUE);
		registerColor("MIDNIGHT_GREEN", MIDNIGHT_GREEN);
		registerColor("MIKADO_YELLOW", MIKADO_YELLOW);
		registerColor("MIMI_PINK", MIMI_PINK);
		registerColor("MINDARO", MINDARO);
		registerColor("MING", MING);
		registerColor("MINION_YELLOW", MINION_YELLOW);
		registerColor("MINT", MINT);
		registerColor("MINT_CREAM", MINT_CREAM);
		registerColor("MINT_GREEN", MINT_GREEN);
		registerColor("MISTY_MOSS", MISTY_MOSS);
		registerColor("MISTY_ROSE", MISTY_ROSE);
		registerColor("MOCCASIN", MOCCASIN);
		registerColor("MODE_BEIGE", MODE_BEIGE);
		registerColor("MONA_LISA", MONA_LISA);
		registerColor("MORNING_BLUE", MORNING_BLUE);
		registerColor("MOSS_GREEN", MOSS_GREEN);
		registerColor("MOUNTAIN_MEADOW", MOUNTAIN_MEADOW);
		registerColor("MOUNTBATTEN_PINK", MOUNTBATTEN_PINK);
		registerColor("MULBERRY", MULBERRY);
		registerColor("MUSTARD", MUSTARD);
		registerColor("MYRTLE_GREEN", MYRTLE_GREEN);
		registerColor("MYSTIC", MYSTIC);
		registerColor("MYSTIC_MAROON", MYSTIC_MAROON);
		registerColor("NADESHIKO_PINK", NADESHIKO_PINK);
		registerColor("NAPLES_YELLOW", NAPLES_YELLOW);
		registerColor("NAVAJO_WHITE", NAVAJO_WHITE);
		registerColor("NAVY_BLUE", NAVY_BLUE);
		registerColor("NEON_BLUE", NEON_BLUE);
		registerColor("NEON_FUCHSIA", NEON_FUCHSIA);
		registerColor("NEON_GREEN", NEON_GREEN);
		registerColor("NEW_CAR", NEW_CAR);
		registerColor("NEW_YORK_PINK", NEW_YORK_PINK);
		registerColor("NICKEL", NICKEL);
		registerColor("NON_PHOTO_BLUE", NON_PHOTO_BLUE);
		registerColor("NYANZA", NYANZA);
		registerColor("OU_CRIMSON_RED", OU_CRIMSON_RED);
		registerColor("OCHRE", OCHRE);
		registerColor("OLD_BURGUNDY", OLD_BURGUNDY);
		registerColor("OLD_GOLD", OLD_GOLD);
		registerColor("OLD_LACE", OLD_LACE);
		registerColor("OLD_LAVENDER", OLD_LAVENDER);
		registerColor("OLD_MAUVE", OLD_MAUVE);
		registerColor("OLD_ROSE", OLD_ROSE);
		registerColor("OLD_SILVER", OLD_SILVER);
		registerColor("OLIVE", OLIVE);
		registerColor("OLIVE_DRAB_7", OLIVE_DRAB_7);
		registerColor("OLIVE_DRAB", OLIVE_DRAB);
		registerColor("OLIVE_GREEN", OLIVE_GREEN);
		registerColor("OLIVINE", OLIVINE);
		registerColor("ONYX", ONYX);
		registerColor("OPAL", OPAL);
		registerColor("OPERA_MAUVE", OPERA_MAUVE);
		registerColor("ORANGE", ORANGE);
		registerColor("ORANGE_JUICE", ORANGE_JUICE);
		registerColor("ORANGE_PEEL", ORANGE_PEEL);
		registerColor("ORANGE_SODA", ORANGE_SODA);
		registerColor("ORANGE_RED", ORANGE_RED);
		registerColor("ORANGE_YELLOW", ORANGE_YELLOW);
		registerColor("ORCHID", ORCHID);
		registerColor("ORCHID_PINK", ORCHID_PINK);
		registerColor("OUTER_SPACE", OUTER_SPACE);
		registerColor("OUTRAGEOUS_ORANGE", OUTRAGEOUS_ORANGE);
		registerColor("OXBLOOD", OXBLOOD);
		registerColor("OXFORD_BLUE", OXFORD_BLUE);
		registerColor("PACIFIC_BLUE", PACIFIC_BLUE);
		registerColor("PAKISTAN_GREEN", PAKISTAN_GREEN);
		registerColor("PALATINATE_PURPLE", PALATINATE_PURPLE);
		registerColor("PALE_DOGWOOD", PALE_DOGWOOD);
		registerColor("PALE_AQUA", PALE_AQUA);
		registerColor("PALE_CERULEAN", PALE_CERULEAN);
		registerColor("PALE_PINK", PALE_PINK);
		registerColor("PALE_PURPLE", PALE_PURPLE);
		registerColor("PALE_SPRING_BUD", PALE_SPRING_BUD);
		registerColor("PANSY_PURPLE", PANSY_PURPLE);
		registerColor("PAOLO_VERONESE_GREEN", PAOLO_VERONESE_GREEN);
		registerColor("PAPAYA_WHIP", PAPAYA_WHIP);
		registerColor("PARADISE_PINK", PARADISE_PINK);
		registerColor("PARCHMENT", PARCHMENT);
		registerColor("PARIS_GREEN", PARIS_GREEN);
		registerColor("PASTEL_PINK", PASTEL_PINK);
		registerColor("PATRIARCH", PATRIARCH);
		registerColor("PAUA", PAUA);
		registerColor("PAYNES_GREY", PAYNES_GREY);
		registerColor("PEACH", PEACH);
		registerColor("PEACH_PUFF", PEACH_PUFF);
		registerColor("PEAR", PEAR);
		registerColor("PEARLY_PURPLE", PEARLY_PURPLE);
		registerColor("PERIWINKLE", PERIWINKLE);
		registerColor("PERMANENT_GERANIUM_LAKE", PERMANENT_GERANIUM_LAKE);
		registerColor("PERSIAN_BLUE", PERSIAN_BLUE);
		registerColor("PERSIAN_GREEN", PERSIAN_GREEN);
		registerColor("PERSIAN_INDIGO", PERSIAN_INDIGO);
		registerColor("PERSIAN_ORANGE", PERSIAN_ORANGE);
		registerColor("PERSIAN_PINK", PERSIAN_PINK);
		registerColor("PERSIAN_PLUM", PERSIAN_PLUM);
		registerColor("PERSIAN_RED", PERSIAN_RED);
		registerColor("PERSIAN_ROSE", PERSIAN_ROSE);
		registerColor("PERSIMMON", PERSIMMON);
		registerColor("PEWTER_BLUE", PEWTER_BLUE);
		registerColor("PHLOX", PHLOX);
		registerColor("PHTHALO_BLUE", PHTHALO_BLUE);
		registerColor("PHTHALO_GREEN", PHTHALO_GREEN);
		registerColor("PICOTEE_BLUE", PICOTEE_BLUE);
		registerColor("PICTORIAL_CARMINE", PICTORIAL_CARMINE);
		registerColor("PIGGY_PINK", PIGGY_PINK);
		registerColor("PINE_GREEN", PINE_GREEN);
		registerColor("PINK", PINK);
		registerColor("PINK_SHERBET", PINK_SHERBET);
		registerColor("PINK_LACE", PINK_LACE);
		registerColor("PINK_LAVENDER", PINK_LAVENDER);
		registerColor("PISTACHIO", PISTACHIO);
		registerColor("PLATINUM", PLATINUM);
		registerColor("PLUM", PLUM);
		registerColor("PLUMP_PURPLE", PLUMP_PURPLE);
		registerColor("POLISHED_PINE", POLISHED_PINE);
		registerColor("POMP_AND_POWER", POMP_AND_POWER);
		registerColor("POPSTAR", POPSTAR);
		registerColor("PORTLAND_ORANGE", PORTLAND_ORANGE);
		registerColor("POWDER_BLUE", POWDER_BLUE);
		registerColor("PRAIRIE_GOLD", PRAIRIE_GOLD);
		registerColor("PRINCETON_ORANGE", PRINCETON_ORANGE);
		registerColor("PRUNE", PRUNE);
		registerColor("PRUSSIAN_BLUE", PRUSSIAN_BLUE);
		registerColor("PSYCHEDELIC_PURPLE", PSYCHEDELIC_PURPLE);
		registerColor("PUCE", PUCE);
		registerColor("PULLMAN_BROWN", PULLMAN_BROWN);
		registerColor("PUMPKIN", PUMPKIN);
		registerColor("PURPLE", PURPLE);
		registerColor("PURPLE_PLUM", PURPLE_PLUM);
		registerColor("PURPLE_MOUNTAIN_MAJESTY", PURPLE_MOUNTAIN_MAJESTY);
		registerColor("PURPLE_NAVY", PURPLE_NAVY);
		registerColor("PURPLE_PIZZAZZ", PURPLE_PIZZAZZ);
		registerColor("QUEEN_BLUE", QUEEN_BLUE);
		registerColor("QUEEN_PINK", QUEEN_PINK);
		registerColor("QUICK_SILVER", QUICK_SILVER);
		registerColor("QUINACRIDONE_MAGENTA", QUINACRIDONE_MAGENTA);
		registerColor("RADICAL_RED", RADICAL_RED);
		registerColor("RAISIN_BLACK", RAISIN_BLACK);
		registerColor("RAJAH", RAJAH);
		registerColor("RASPBERRY", RASPBERRY);
		registerColor("RASPBERRY_GLACÉ", RASPBERRY_GLACÉ);
		registerColor("RASPBERRY_ROSE", RASPBERRY_ROSE);
		registerColor("RAW_SIENNA", RAW_SIENNA);
		registerColor("RAW_UMBER", RAW_UMBER);
		registerColor("RAZZLE_DAZZLE_ROSE", RAZZLE_DAZZLE_ROSE);
		registerColor("RAZZMATAZZ", RAZZMATAZZ);
		registerColor("RAZZMIC_BERRY", RAZZMIC_BERRY);
		registerColor("REBECCA_PURPLE", REBECCA_PURPLE);
		registerColor("RED", RED);
		registerColor("RED_SALSA", RED_SALSA);
		registerColor("RED_OCHRE", RED_OCHRE);
		registerColor("RED_ORANGE", RED_ORANGE);
		registerColor("RED_PURPLE", RED_PURPLE);
		registerColor("RED_VIOLET", RED_VIOLET);
		registerColor("REDWOOD", REDWOOD);
		registerColor("RESOLUTION_BLUE", RESOLUTION_BLUE);
		registerColor("RHYTHM", RHYTHM);
		registerColor("RICH_BLACK", RICH_BLACK);
		registerColor("RIFLE_GREEN", RIFLE_GREEN);
		registerColor("ROBIN_EGG_BLUE", ROBIN_EGG_BLUE);
		registerColor("ROCKET_METALLIC", ROCKET_METALLIC);
		registerColor("ROJO_SPANISH_RED", ROJO_SPANISH_RED);
		registerColor("ROMAN_SILVER", ROMAN_SILVER);
		registerColor("ROSE", ROSE);
		registerColor("ROSE_DUST", ROSE_DUST);
		registerColor("ROSE_POMPADOUR", ROSE_POMPADOUR);
		registerColor("ROSE_BONBON", ROSE_BONBON);
		registerColor("ROSE_EBONY", ROSE_EBONY);
		registerColor("ROSE_MADDER", ROSE_MADDER);
		registerColor("ROSE_PINK", ROSE_PINK);
		registerColor("ROSE_RED", ROSE_RED);
		registerColor("ROSE_TAUPE", ROSE_TAUPE);
		registerColor("ROSE_VALE", ROSE_VALE);
		registerColor("ROSEWOOD", ROSEWOOD);
		registerColor("ROSSO_CORSA", ROSSO_CORSA);
		registerColor("ROSY_BROWN", ROSY_BROWN);
		registerColor("ROYAL_BLUE", ROYAL_BLUE);
		registerColor("ROYAL_PURPLE", ROYAL_PURPLE);
		registerColor("ROYAL_YELLOW", ROYAL_YELLOW);
		registerColor("RUBER", RUBER);
		registerColor("RUBINE_RED", RUBINE_RED);
		registerColor("RUBY", RUBY);
		registerColor("RUBY_RED", RUBY_RED);
		registerColor("RUFOUS", RUFOUS);
		registerColor("RUSSET", RUSSET);
		registerColor("RUSSIAN_GREEN", RUSSIAN_GREEN);
		registerColor("RUSSIAN_VIOLET", RUSSIAN_VIOLET);
		registerColor("RUST", RUST);
		registerColor("RUSTY_RED", RUSTY_RED);
		registerColor("SACRAMENTO_STATE_GREEN", SACRAMENTO_STATE_GREEN);
		registerColor("SADDLE_BROWN", SADDLE_BROWN);
		registerColor("SAFETY_ORANGE", SAFETY_ORANGE);
		registerColor("SAFETY_YELLOW", SAFETY_YELLOW);
		registerColor("SAFFRON", SAFFRON);
		registerColor("SAGE", SAGE);
		registerColor("SALMON", SALMON);
		registerColor("SALMON_PINK", SALMON_PINK);
		registerColor("SAND", SAND);
		registerColor("SAND_DUNE", SAND_DUNE);
		registerColor("SANDY_BROWN", SANDY_BROWN);
		registerColor("SAP_GREEN", SAP_GREEN);
		registerColor("SAPPHIRE", SAPPHIRE);
		registerColor("SAPPHIRE_BLUE", SAPPHIRE_BLUE);
		registerColor("SATIN_SHEEN_GOLD", SATIN_SHEEN_GOLD);
		registerColor("SCARLET", SCARLET);
		registerColor("SCHAUSS_PINK", SCHAUSS_PINK);
		registerColor("SCHOOL_BUS_YELLOW", SCHOOL_BUS_YELLOW);
		registerColor("SCREAMIN_GREEN", SCREAMIN_GREEN);
		registerColor("SEA_GREEN", SEA_GREEN);
		registerColor("SEAL_BROWN", SEAL_BROWN);
		registerColor("SEANCE", SEANCE);
		registerColor("SEASHELL", SEASHELL);
		registerColor("SECRET", SECRET);
		registerColor("SELECTIVE_YELLOW", SELECTIVE_YELLOW);
		registerColor("SEPIA", SEPIA);
		registerColor("SHADOW", SHADOW);
		registerColor("SHADOW_BLUE", SHADOW_BLUE);
		registerColor("SHAMROCK_GREEN", SHAMROCK_GREEN);
		registerColor("SHEEN_GREEN", SHEEN_GREEN);
		registerColor("SHIMMERING_BLUSH", SHIMMERING_BLUSH);
		registerColor("SHINY_SHAMROCK", SHINY_SHAMROCK);
		registerColor("SHOCKING_PINK", SHOCKING_PINK);
		registerColor("SIENNA", SIENNA);
		registerColor("SILVER", SILVER);
		registerColor("SILVER_CHALICE", SILVER_CHALICE);
		registerColor("SILVER_PINK", SILVER_PINK);
		registerColor("SILVER_SAND", SILVER_SAND);
		registerColor("SINOPIA", SINOPIA);
		registerColor("SIZZLING_RED", SIZZLING_RED);
		registerColor("SIZZLING_SUNRISE", SIZZLING_SUNRISE);
		registerColor("SKOBELOFF", SKOBELOFF);
		registerColor("SKY_BLUE", SKY_BLUE);
		registerColor("SKY_MAGENTA", SKY_MAGENTA);
		registerColor("SLATE_BLUE", SLATE_BLUE);
		registerColor("SLATE_GRAY", SLATE_GRAY);
		registerColor("SLIMY_GREEN", SLIMY_GREEN);
		registerColor("SMITTEN", SMITTEN);
		registerColor("SMOKY_BLACK", SMOKY_BLACK);
		registerColor("SNOW", SNOW);
		registerColor("SOLID_PINK", SOLID_PINK);
		registerColor("SONIC_SILVER", SONIC_SILVER);
		registerColor("SPACE_CADET", SPACE_CADET);
		registerColor("SPANISH_BISTRE", SPANISH_BISTRE);
		registerColor("SPANISH_BLUE", SPANISH_BLUE);
		registerColor("SPANISH_CARMINE", SPANISH_CARMINE);
		registerColor("SPANISH_GRAY", SPANISH_GRAY);
		registerColor("SPANISH_GREEN", SPANISH_GREEN);
		registerColor("SPANISH_ORANGE", SPANISH_ORANGE);
		registerColor("SPANISH_PINK", SPANISH_PINK);
		registerColor("SPANISH_RED", SPANISH_RED);
		registerColor("SPANISH_SKY_BLUE", SPANISH_SKY_BLUE);
		registerColor("SPANISH_VIOLET", SPANISH_VIOLET);
		registerColor("SPANISH_VIRIDIAN", SPANISH_VIRIDIAN);
		registerColor("SPRING_FROST", SPRING_FROST);
		registerColor("SPRING_BUD", SPRING_BUD);
		registerColor("SPRING_GREEN", SPRING_GREEN);
		registerColor("ST_PATRICKS_BLUE", ST_PATRICKS_BLUE);
		registerColor("STAR_COMMAND_BLUE", STAR_COMMAND_BLUE);
		registerColor("STEEL_BLUE", STEEL_BLUE);
		registerColor("STEEL_PINK", STEEL_PINK);
		registerColor("STIL_DE_GRAIN_YELLOW", STIL_DE_GRAIN_YELLOW);
		registerColor("STRAW", STRAW);
		registerColor("STRAWBERRY", STRAWBERRY);
		registerColor("STRAWBERRY_BLONDE", STRAWBERRY_BLONDE);
		registerColor("STRONG_LIME_GREEN", STRONG_LIME_GREEN);
		registerColor("SUGAR_PLUM", SUGAR_PLUM);
		registerColor("SUNGLOW", SUNGLOW);
		registerColor("SUNRAY", SUNRAY);
		registerColor("SUNSET", SUNSET);
		registerColor("SUPER_PINK", SUPER_PINK);
		registerColor("SWEET_BROWN", SWEET_BROWN);
		registerColor("SYRACUSE_ORANGE", SYRACUSE_ORANGE);
		registerColor("TAN", TAN);
		registerColor("TANGERINE", TANGERINE);
		registerColor("TANGO_PINK", TANGO_PINK);
		registerColor("TART_ORANGE", TART_ORANGE);
		registerColor("TAUPE", TAUPE);
		registerColor("TAUPE_GRAY", TAUPE_GRAY);
		registerColor("TEA_GREEN", TEA_GREEN);
		registerColor("TEA_ROSE", TEA_ROSE);
		registerColor("TEAL", TEAL);
		registerColor("TEAL_BLUE", TEAL_BLUE);
		registerColor("TECHNOBOTANICA", TECHNOBOTANICA);
		registerColor("TELEMAGENTA", TELEMAGENTA);
		registerColor("TENNÉ", TENNÉ);
		registerColor("TERRA_COTTA", TERRA_COTTA);
		registerColor("THISTLE", THISTLE);
		registerColor("THULIAN_PINK", THULIAN_PINK);
		registerColor("TICKLE_ME_PINK", TICKLE_ME_PINK);
		registerColor("TIFFANY_BLUE", TIFFANY_BLUE);
		registerColor("TIMBERWOLF", TIMBERWOLF);
		registerColor("TITANIUM_YELLOW", TITANIUM_YELLOW);
		registerColor("TOMATO", TOMATO);
		registerColor("TOURMALINE", TOURMALINE);
		registerColor("TROPICAL_RAINFOREST", TROPICAL_RAINFOREST);
		registerColor("TRUE_BLUE", TRUE_BLUE);
		registerColor("TRYPAN_BLUE", TRYPAN_BLUE);
		registerColor("TUFTS_BLUE", TUFTS_BLUE);
		registerColor("TUMBLEWEED", TUMBLEWEED);
		registerColor("TURQUOISE", TURQUOISE);
		registerColor("TURQUOISE_BLUE", TURQUOISE_BLUE);
		registerColor("TURQUOISE_GREEN", TURQUOISE_GREEN);
		registerColor("TURTLE_GREEN", TURTLE_GREEN);
		registerColor("TUSCAN", TUSCAN);
		registerColor("TUSCAN_BROWN", TUSCAN_BROWN);
		registerColor("TUSCAN_RED", TUSCAN_RED);
		registerColor("TUSCAN_TAN", TUSCAN_TAN);
		registerColor("TUSCANY", TUSCANY);
		registerColor("TWILIGHT_LAVENDER", TWILIGHT_LAVENDER);
		registerColor("TYRIAN_PURPLE", TYRIAN_PURPLE);
		registerColor("UA_BLUE", UA_BLUE);
		registerColor("UA_RED", UA_RED);
		registerColor("UP_FOREST_GREEN", UP_FOREST_GREEN);
		registerColor("UP_MAROON", UP_MAROON);
		registerColor("USAFA_BLUE", USAFA_BLUE);
		registerColor("ULTRA_PINK", ULTRA_PINK);
		registerColor("ULTRA_RED", ULTRA_RED);
		registerColor("ULTRAMARINE", ULTRAMARINE);
		registerColor("ULTRAMARINE_BLUE", ULTRAMARINE_BLUE);
		registerColor("UMBER", UMBER);
		registerColor("UNBLEACHED_SILK", UNBLEACHED_SILK);
		registerColor("UNITED_NATIONS_BLUE", UNITED_NATIONS_BLUE);
		registerColor("UNIVERSITY_OF_PENNSYLVANIA_RED", UNIVERSITY_OF_PENNSYLVANIA_RED);
		registerColor("UNMELLOW_YELLOW", UNMELLOW_YELLOW);
		registerColor("UPSDELL_RED", UPSDELL_RED);
		registerColor("URANIAN_BLUE", URANIAN_BLUE);
		registerColor("VAN_DYKE_BROWN", VAN_DYKE_BROWN);
		registerColor("VANILLA", VANILLA);
		registerColor("VANILLA_ICE", VANILLA_ICE);
		registerColor("VEGAS_GOLD", VEGAS_GOLD);
		registerColor("VENETIAN_RED", VENETIAN_RED);
		registerColor("VERDIGRIS", VERDIGRIS);
		registerColor("VERMILION", VERMILION);
		registerColor("VERONICA", VERONICA);
		registerColor("VIOLET", VIOLET);
		registerColor("VIOLET_BLUE", VIOLET_BLUE);
		registerColor("VIOLET_RED", VIOLET_RED);
		registerColor("VIRIDIAN", VIRIDIAN);
		registerColor("VIRIDIAN_GREEN", VIRIDIAN_GREEN);
		registerColor("VIVID_BURGUNDY", VIVID_BURGUNDY);
		registerColor("VIVID_SKY_BLUE", VIVID_SKY_BLUE);
		registerColor("VIVID_TANGERINE", VIVID_TANGERINE);
		registerColor("VIVID_VIOLET", VIVID_VIOLET);
		registerColor("VOLT", VOLT);
		registerColor("WARM_BLACK", WARM_BLACK);
		registerColor("WEEZY_BLUE", WEEZY_BLUE);
		registerColor("WHEAT", WHEAT);
		registerColor("WHITE", WHITE);
		registerColor("WILD_STRAWBERRY", WILD_STRAWBERRY);
		registerColor("WILD_BLUE_YONDER", WILD_BLUE_YONDER);
		registerColor("WILD_ORCHID", WILD_ORCHID);
		registerColor("WILD_WATERMELON", WILD_WATERMELON);
		registerColor("WINDSOR_TAN", WINDSOR_TAN);
		registerColor("WINE", WINE);
		registerColor("WINE_DREGS", WINE_DREGS);
		registerColor("WINTER_SKY", WINTER_SKY);
		registerColor("WINTERGREEN_DREAM", WINTERGREEN_DREAM);
		registerColor("WISTERIA", WISTERIA);
		registerColor("WOOD_BROWN", WOOD_BROWN);
		registerColor("XANADU", XANADU);
		registerColor("XANTHIC", XANTHIC);
		registerColor("XANTHOUS", XANTHOUS);
		registerColor("YINMN_BLUE", YINMN_BLUE);
		registerColor("YALE_BLUE", YALE_BLUE);
		registerColor("YELLOW", YELLOW);
		registerColor("YELLOW_ORANGE", YELLOW_ORANGE);
		registerColor("YELLOW_SUNSHINE", YELLOW_SUNSHINE);
		registerColor("YELLOW_GREEN", YELLOW_GREEN);
		registerColor("ZAFFRE", ZAFFRE);
		registerColor("ZINNWALDITE_BROWN", ZINNWALDITE_BROWN);
		registerColor("ZOMP", ZOMP);

		registerColor("AO", AO);
		registerColor("BRIGHT_CERULEAN", BRIGHT_CERULEAN);
		registerColor("CINDER", CINDER);
		registerColor("CRYSTAL_BLUE", CRYSTAL_BLUE);
		registerColor("CRYSTAL_GREEN", CRYSTAL_GREEN);
		registerColor("DARK_BLUE", DARK_BLUE);
		registerColor("FORSYTHIA", FORSYTHIA);
		registerColor("HOT_PEPPER_GREEN", HOT_PEPPER_GREEN);
		registerColor("LAVENDER_MIST", LAVENDER_MIST);
		registerColor("LIGHT_SLATE_BLUE", LIGHT_SLATE_BLUE);
		registerColor("MYRTLE", MYRTLE);
		registerColor("SWAMP_MOSS", SWAMP_MOSS);
	}
}
