name: Build and Package All Platforms

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  package_macos:
    needs: build
    uses: ./.github/workflows/package-macos-postbuild.yml

  package_windows:
    needs: build
    uses: ./.github/workflows/package-windows-postbuild.yml

