name: Package Windows Apps

on:
  workflow_call:

jobs:
  package:
    runs-on: windows-latest

    steps:
      - name: Download JAR Artifacts
        uses: actions/download-artifact@v4
        with:
          name: jar-files

      - name: Package GeometricFractalsApp for Windows
        run: |
          jpackage ^
            --input . ^
            --name GeometricFractalsApp ^
            --main-jar GeometricFractalsApp.jar ^
            --main-class gui.GeometricFractalsApp ^
            --type exe ^
            --app-version 1.0.0
        shell: cmd

      - name: Package LSystemFractalsApp for Windows
        run: |
          jpackage ^
            --input . ^
            --name LSystemFractalsApp ^
            --main-jar LSystemFractalsApp.jar ^
            --main-class gui.LSystemFractalsApp ^
            --type exe ^
            --app-version 1.0.0
        shell: cmd

      - name: Upload Windows EXE Files
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe-files
          path: '*.exe'

