name: Package Windows Apps

on:
  workflow_call:

jobs:
  package:
    runs-on: windows-latest

    steps:
      - name: Set up Java 17 with jpackage
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Download JAR Artifacts
        uses: actions/download-artifact@v4
        with:
          name: jar-files

      - name: Prepare Input Folder for GeometricFractalsApp
        run: |
          if exist geometric-input rmdir /s /q geometric-input
          mkdir geometric-input
          copy GeometricFractalsApp.jar geometric-input
        shell: cmd

      - name: Package GeometricFractalsApp for Windows
        run: |
          jpackage ^
            --input geometric-input ^
            --name GeometricFractalsApp ^
            --main-jar GeometricFractalsApp.jar ^
            --main-class gui.GeometricFractalsApp ^
            --type exe ^
            --app-version 1.0.0
        shell: cmd

      - name: Prepare Input Folder for LSystemFractalsApp
        run: |
          if exist lsystem-input rmdir /s /q lsystem-input
          mkdir lsystem-input
          copy LSystemFractalsApp.jar lsystem-input
        shell: cmd

      - name: Package LSystemFractalsApp for Windows
        run: |
          jpackage ^
            --input lsystem-input ^
            --name LSystemFractalsApp ^
            --main-jar LSystemFractalsApp.jar ^
            --main-class gui.LSystemFractalsApp ^
            --type exe ^
            --app-version 1.0.0
        shell: cmd

      - name: Upload Windows EXE Files
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe-files
          path: '*.exe'

